### ISSUE TITLE
Problem with group selection for a user

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1003]
**How to reproduce:**

1.  Add a user to a group (say 'TestGroup1').
2.  Login with the user's account and change to newly assigned group (TestGroup1) and logout.
3.  Remove the user from the same group (TestGroup1).
4.  Login again with the user's account.

No information will be displayed and the Ajax query get struck as the user have no permissions in the group (TestGroup1). Since the user is a part of only group now, he/she can not change the group to solve the issue.

![2018-03-15 09_52_05-browse](https://user-images.githubusercontent.com/18077542/37444333-f132ebb6-2836-11e8-9c63-13217f6edd3e.png)

**Expected result:**

If the user is removed from the group, it should also be reflected in the selected group when the user logs in again.

**Comment by GMishx** [comment]
Got the following error in my apache error log:

`PHP Fatal error:  Uncaught Exception: You are assigned to wrong group. in /usr/local/share/fossology/www/ui/async/AjaxBrowse.php:77\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(243): Fossology\\UI\\Ajax\\AjaxBrowse->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#1 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(275): Fossology\\Lib\\Plugin\\DefaultPlugin->getResponse()\n#2 /usr/local/share/fossology/www/ui/index.php(62): Fossology\\Lib\\Plugin\\DefaultPlugin->execute()\n#3 {main}\n  thrown in /usr/local/share/fossology/www/ui/async/AjaxBrowse.php on line 77, referer: http://localhost/foss/?mod=browse`
