### ISSUE TITLE
reportImport job is killed before import of RDF file is completed

### ISSUE THREAD

**Issue by swinslow** [fossology/fossology#1136]
Hello,
On a 3.3.0 install of Fossology using the Debian packages, I am trying to import a large (>200MB) RDF file that was exported from a prior install.

The import begins successfully, but before it is able to finish, the job is killed by the heartbeat tracker. It looks like this is happening at [/src/scheduler/agent/agent.c](https://github.com/fossology/fossology/blob/master/src/scheduler/agent/agent.c) line 155.

Can the reportImport job be modified so that it continues to send the heartbeat, even for long-running large imports? Alternatively, is there any way to modify the value of `CONF_agent_death_timer` without recompiling from source?

Log from this job is as follows:
```
2018-07-04 00:03:00 reportImport [0] :: JOB[43].reportImport[1900.localhost]: "DEBUG: unrefined $longArgs are: 1530657619_581922685_SPDX2_testfile-2018-06-21-180914.zip_1530629222-spdx.rdf --addConcludedAsDecisions=true --addLicenseInfoFromConcluded=true --addConcludedAsDecisionsOverwrite=true --addNewLicensesAs=license"
2018-07-04 00:03:00 reportImport [0] :: JOB[43].reportImport[1900.localhost]: "INFO: $createLicensesAsCandidate is: bool(false)"
2018-07-04 00:03:00 reportImport [0] :: JOB[43].reportImport[1900.localhost]: "INFO: $createLicensesInfosAsFindings is: bool(false)"
2018-07-04 00:03:00 reportImport [0] :: JOB[43].reportImport[1900.localhost]: "INFO: $createConcludedLicensesAsFindings is: bool(true)"
2018-07-04 00:03:00 reportImport [0] :: JOB[43].reportImport[1900.localhost]: "INFO: $createConcludedLicensesAsConclusions is: bool(true)"
2018-07-04 00:03:00 reportImport [0] :: JOB[43].reportImport[1900.localhost]: "INFO: $overwriteDecisions is: bool(true)"
2018-07-04 00:03:00 reportImport [0] :: JOB[43].reportImport[1900.localhost]: "INFO: $addCopyrightInformation is: bool(false)"
2018-07-04 00:03:00 reportImport [0] :: JOB[43].reportImport[1900.localhost]: "INFO: $concludeLicenseDecisionType is: int(5)"
2018-07-04 00:07:01 reportImport [0] :: JOB[43].reportImport[1900.localhost]: no heartbeat for 241 seconds
2018-07-04 00:07:02 reportImport [0] :: JOB[43].reportImport[1900.localhost]: agent was killed by signal: 9.Killed
```

**Comment by GMishx** [comment]
Hello @swinslow ,

You can refer to test file at [src/scheduler/agent_tests/agents/fossology.conf.in](https://github.com/fossology/fossology/blob/master/src/scheduler/agent_tests/agents/fossology.conf.in#L35) for sample value and formats under `[SCHEDULER]` section.

You can set the agent_death_timer to something more than 180 (which is current value) and restarting the fossology scheduler using `sudo service fossology restart`.

It will be picked-up by the [this macro](https://github.com/fossology/fossology/blob/master/src/scheduler/agent/scheduler.h#L160) which is called during the [fossology initialization](https://github.com/fossology/fossology/blob/master/src/scheduler/agent/scheduler.c#L923).

Please let us know if this solves your issue.

**Comment by swinslow** [comment]
Hi Gaurav,

Thanks very much. I will try this out and will let you know if it resolves
the issue.
Also, I notice that the imported RDF files are copied to
/srv/fossology/repository/ReportImport/ (on my server anyway). Is there any
need to retain these files after the import is successfully completed? Or
can the files be deleted from this directory?

Best,
Steve

**Comment by shaheemazmalmmd** [comment]
Hello Steve,

The RDF files are stored in `/srv/fossology/repository/ReportImport/` for further download of the same file in future. 

So there is no need to keep this file, you can delete it once the agent ReportImport is through.

**Comment by mcjaeger** [comment]
@swinslow safe to close this issue?

**Comment by swinslow** [comment]
@mcjaeger I haven't had a chance yet to re-try this with a large file to import; I may have the opportunity to try it with a couple within the next few weeks, but not immediately. 

If you want to go ahead and close it, I'm okay with that. I can re-open if I still see problems in the future after creating / modifying the [SCHEDULER] section as recommended. 

However, I'd note that we may want to document more prominently in the Fossology docs about the need to create or modify this [SCHEDULER] section. I saw that #518 also had a similar issue for a different agent. If the default values are resulting in various agents being killed, I wonder if we might want to increase the defaults so that newcomers to Fossology aren't caught off-guard when jobs fail without a clear way to address the issue.

**Comment by swinslow** [comment]
Looping back on this old issue: I'm now on 3.8.1 and reportImport is not showing the errors I reported above. However, I am instead seeing a "No memory" error even when running a much smaller RDF file (about 14.4MB):

```
2020-07-21 20:13:34 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "DEBUG: unrefined $longArgs are: 1595362414_840161834_policy-2020-07-13.rdf --addConcludedAsDecisions=true --addConcludedAsDecisionsOverwrite=true --addNewLicensesAs=license"
2020-07-21 20:13:34 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "INFO: $createLicensesAsCandidate is: bool(false)"
2020-07-21 20:13:34 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "INFO: $createLicensesInfosAsFindings is: bool(false)"
2020-07-21 20:13:34 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "INFO: $createConcludedLicensesAsFindings is: bool(false)"
2020-07-21 20:13:34 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "INFO: $createConcludedLicensesAsConclusions is: bool(true)"
2020-07-21 20:13:34 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "INFO: $overwriteDecisions is: bool(true)"
2020-07-21 20:13:34 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "INFO: $addCopyrightInformation is: bool(false)"
2020-07-21 20:13:34 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "INFO: $concludeLicenseDecisionType is: int(5)"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "Caught exception while processing uploadId=31: XML error: "No memory" on line 238899, column 1#0 /usr/share/fossology/vendor/easyrdf/easyrdf/lib/EasyRdf/Graph.php(234): EasyRdf_Parser_RdfXml->parse(Object(EasyRdf_Graph), 'parse('parseFile('/mnt/volume_nyc...', 'rdfxml', 'file:///mnt/vol...')"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#3 /usr/share/fossology/reportImport/agent/SpdxTwoImportSource.php(54): Fossology\ReportImport\SpdxTwoImportSource->loadGraph('/mnt/volume_nyc...', NULL)"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#4 /usr/share/fossology/reportImport/agent/ReportImportAgent.php(259): Fossology\ReportImport\SpdxTwoImportSource->parse()"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#5 /usr/share/fossology/reportImport/agent/ReportImportAgent.php(272): Fossology\ReportImport\ReportImportAgent->getImportSource('/mnt/volume_nyc...')"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#6 /usr/share/fossology/reportImport/agent/ReportImportAgent.php(149): Fossology\ReportImport\ReportImportAgent->walkAllFiles('/mnt/volume_nyc...', 31, Object(Fossology\ReportImport\ReportImportConfiguration))"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#7 /usr/share/fossology/lib/php/Agent/Agent.php(338): Fossology\ReportImport\ReportImportAgent->processUploadId(31)"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#8 /usr/share/fossology/reportImport/agent/reportImport.php(24): Fossology\Lib\Agent\Agent->run_scheduler_event_loop()"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#9 /usr/lib/fossology/fo_wrapper(77): require('/usr/share/foss...')"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#10 {main}agent failed on uploadId=31#0  Fossology\Lib\Agent\Agent->bail() called at [/usr/share/fossology/lib/php/Agent/Agent.php:349]"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#1  Fossology\Lib\Agent\Agent->run_scheduler_event_loop() called at [/usr/share/fossology/reportImport/agent/reportImport.php:24]"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: "#2  require(/usr/share/fossology/reportImport/agent/reportImport.php) called at [/usr/lib/fossology/fo_wrapper:77]"
2020-07-21 20:13:41 reportImport [0] :: JOB[744].reportImport[9360.localhost]: agent failed with error code 1
2020-07-21 20:13:42 reportImport [0] :: JOB[744].reportImport[9360.localhost]: agent failed, code: 0
```

@mcjaeger or @GMishx, do you know if there is a way to increase the memory available to the reportImport agent so it does not fail here?

**Comment by janwels89** [comment]
I can confirm this problem still exists with large rdf-files (complete qt source code)
```
2021-01-25 08:01:41 reportImport [0] :: JOB[398].reportImport[26947.localhost]: "DEBUG: unrefined $longArgs are: 1611561698_1470917597_SPDX2_5.2.1_win.7z_1611561306-spdx.rdf --addConcludedAsDecisions=true --addLicenseInfoFromInfoInFile=true --addLicenseInfoFromConcluded=true --addConcludedAsDecisionsOverwrite=true --addConcludedAsDecisionsTBD=true --addNewLicensesAs=candidate"
2021-01-25 08:01:41 reportImport [0] :: JOB[398].reportImport[26947.localhost]: "INFO: $createLicensesAsCandidate is: bool(true)"
2021-01-25 08:01:41 reportImport [0] :: JOB[398].reportImport[26947.localhost]: "INFO: $createLicensesInfosAsFindings is: bool(true)"
2021-01-25 08:01:41 reportImport [0] :: JOB[398].reportImport[26947.localhost]: "INFO: $createConcludedLicensesAsFindings is: bool(true)"
2021-01-25 08:01:41 reportImport [0] :: JOB[398].reportImport[26947.localhost]: "INFO: $createConcludedLicensesAsConclusions is: bool(true)"
2021-01-25 08:01:41 reportImport [0] :: JOB[398].reportImport[26947.localhost]: "INFO: $overwriteDecisions is: bool(true)"
2021-01-25 08:01:41 reportImport [0] :: JOB[398].reportImport[26947.localhost]: "INFO: $addCopyrightInformation is: bool(false)"
2021-01-25 08:01:41 reportImport [0] :: JOB[398].reportImport[26947.localhost]: "INFO: $concludeLicenseDecisionType is: int(3)"
2021-01-25 08:04:54 reportImport [0] :: JOB[398].reportImport[26947.localhost]: no heartbeat for 193 seconds
2021-01-25 08:04:55 reportImport [0] :: JOB[398].reportImport[26947.localhost]: agent was killed by signal: 9.Killed
```

**Comment by mcjaeger** [comment]
hello,

how many megabytes is the archive and how many the spdx file?

Kind regards, Michael

**Comment by swinslow** [comment]
@mcjaeger When I was seeing this issue back in July (on 3.8.1) it was for an SPDX file that was only about 14.4MB.

**Comment by janwels89** [comment]
@mcjaeger my SPDX-File is 130MB. I scanned a complete qt package (around 2GB)

**Comment by GMishx** [comment]
I did a small research a while back, it is a known issue in the project FOSSology is using to read the SPDX files -> https://github.com/easyrdf/easyrdf/issues/350

However, the fix is in new versions of `easyrdf` which requires PHP 7.1.0. FOSSology currently tags minimum dependency of PHP to 7.0.8 (used by Ubuntu Xenial LTS).
We can try to create a patch from the PRs in the project and apply them during the FOSSology installation (it is BSD-3-Clause licensed).

**Comment by swinslow** [comment]
Thank you @GMishx and others! This will be a huge help.
