### ISSUE TITLE
pg_query(): Query failed: ERROR:  column author.author_pk does not exist

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#1209]
### Description

I don't know, which version it was, but I had an older version of Fossology repo and therefore docker container, which worked without any problems. Yesterday I updated the Fossology repo and created new docker container. Before, I deleted the old ones. 

**One important note**: I have an external PostgreSQL database. So I changed the `docker-compose.yml`, so all DB relevant variables are pointint to the external PostgreSQL database and removed the link to the Docker Postgre container. This database was also used by the old Fossology version.

Now I wanted to run another scan, but nothing happens, i.e. no progress:

![fossology-not-progress](https://user-images.githubusercontent.com/20419801/45741632-62487780-bbf8-11e8-8538-ce65f04112da.png)

When I call `docker ps`, I get this output:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                         PORTS                  NAMES
5317b1eb6c95        fossology           "/fossology/docker..."   17 hours ago        Up 17 hours                    0.0.0.0:8081->80/tcp   fossology_web_1
bf0fd13709cf        fossology           "/fossology/docker..."   17 hours ago        Restarting (255) 2 hours ago                          fossology_scheduler_1
```

#### How to reproduce

Update from an older Fossology version to the latest. As said before, the old version was linked to an external PostgreSQL database and now it uses the same external PostgreSQL database.

### Versions

* Last commit id on master:
`git rev-parse HEAD` gives me `4580ed337fa1cdda26b11d856550876d29f16203`
* Operating System (lsb_release -a):
On my system, `lsb_release` is not there, but when it helps, here is the output of `cat /etc/*-release`:

> NAME="Red Hat Enterprise Linux Server"
> VERSION="7.5 (Maipo)"
> ID="rhel"
> ID_LIKE="fedora"
> VARIANT="Server"
> VARIANT_ID="server"
> VERSION_ID="7.5"
> PRETTY_NAME="Red Hat Enterprise Linux"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
> HOME_URL="https://www.redhat.com/"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> 
> REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
> REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
> REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
> Red Hat Enterprise Linux Server release 7.5 (Maipo)
> Red Hat Enterprise Linux Server release 7.5 (Maipo)

#### Logs

The `docker logs bf` (i.e. the _scheduler_ container) command for the scheduler container gives me this output:

```
NOTE: using external DB on host some.host.local
*** update the database and license_ref table ***
Old release was 3.0.1
*** Cleaning author table ***
PHP Warning:  pg_query(): Query failed: ERROR:  column author.author_pk does not exist
LINE 5: WHERE public.author.author_pk = a.author_pk AND p.pfile_pk I...
              ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 81
Something went wrong. Try running postinstall again!
[2018-09-19 06:09:56] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column author.author_pk does not exist LINE 5: WHERE public.author.author_pk = a.author_pk AND p.pfile_pk I...               ^ [] []
PHP Warning:  pg_query(): Query failed: ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 81
[2018-09-19 06:09:57] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "option_value" of relation "sysconfig" already exists [] []
PHP Fatal error:  Uncaught exception 'Fossology\Lib\Exception' with message 'error executing: ALTER TABLE "sysconfig" ADD COLUMN "option_value" character varying(40) DEFAULT NULL
ERROR:  column "option_value" of relation "sysconfig" already exists' in /usr/local/share/fossology/lib/php/Db/DbManager.php:140
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(204): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "sy...')
#1 /usr/local/share/fossology/lib/php/libschema.php(280): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "sy...')
#2 /usr/local/share/fossology/lib/php/libschema.php(142): fo_libschema->applyTables()
#3 /usr/local/lib/fossology/fossinit.php(169): fo_libschema->applySchema('/usr/local/shar...', false, 'fossology', Array)
#4 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 140

```

#### Fossology logs

Cannot enter in the _scheduler_ container, because this container is stopped.

**Comment by kohldampfer** [comment]
I just digged a little bit in the database of fossology and when I enter `select * from author;`, I get this

```
 ct_pk | agent_fk | pfile_fk | content | hash | type | copy_startbyte | copy_endbyte | is_enabled
-------+----------+----------+---------+------+------+----------------+--------------+------------
(0 rows)
```

So, there is indeed no column `author_pk`. But I do not know, why it is not there.

**Comment by shaheemazmalmmd** [comment]
Hello @kohldampfer , 

Can you run install/fo-postinstall from your fossology folder and try again ?

**Comment by kohldampfer** [comment]
@shaheemazmalmmd 
On my host machine, I only found the file `install/fo-postinstall.in`. Then I thought to try it from a container, so I entered the `fossology_web_1` container with `sudo docker exec -it 62 /bin/bash`. There, I searched for a file called `fo-postinstall`. I found one at `/usr/local/lib/fossology`. I changed into that directory and called the `fo-postinstall` script. This is the output:


```
*** Running postinstall for everything ***
*** Running postinstall for common actions***
*** Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
*** Making sure needed dirs exist with right ownership/permissions ***
*** clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database
 performance improvement. We suggest that you either configure postgres to run its 
autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or 
run Admin > Maintenance on a regular basis.
      Admin > Dashboard will show you the last time vacuum and analyze have been run.
*** Running postinstall for web-only actions***
NOTE: using external DB on host some.host.local
*** update the database and license_ref table ***
Old release was 3.0.1
*** Cleaning author table ***
PHP Warning:  pg_query(): Query failed: ERROR:  column author.author_pk does not exist
LINE 5: WHERE public.author.author_pk = a.author_pk AND p.pfile_pk I...
              ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 81
[2018-09-27 09:44:17] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column author.author_pk does not exist LINE 5: WHERE public.author.author_pk = a.author_pk AND p.pfile_pk I.. ^ [] []
Something went wrong. Try running postinstall again!
PHP Warning:  pg_query(): Query failed: ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 81
[2018-09-27 09:44:18] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "option_value" of relation "sysconfig" already exists [] []
PHP Fatal error:  Uncaught exception 'Fossology\Lib\Exception' with message 'error executing: ALTER TABLE "sysconfig" ADD COLUMN "option_value" character varying(40) DEFAULT NULL ERROR:  column "option_value" of relation "sysconfig" already exists' in /usr/local/share/fossology/lib/php/Db/DbManager.php:140
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(204): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "sy...')
#1 /usr/local/share/fossology/lib/php/libschema.php(280): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "sy...')
#2 /usr/local/share/fossology/lib/php/libschema.php(142): fo_libschema->applyTables()
#3 /usr/local/lib/fossology/fossinit.php(169): fo_libschema->applySchema('/usr/local/shar...', false, 'fossology', Array)
#4 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 140

```
