### ISSUE TITLE
Installing 3.4.0-RC1 packages  on 3.1 crashes at DB update

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1227]
Attempting to install the packages found here:

https://github.com/fossology/fossology/releases/tag/3.4.0-rc1

onto a 3.1 system crashes with the following installation log:

```
*** Running postinstall for web-only actions***
*** update the database and license_ref table ***
Old release was 3.0.1
*** Cleaning author table ***
PHP Warning:  pg_query(): Query failed: ERROR:  column author.author_pk does not exist
LINE 5: WHERE public.author.author_pk = a.author_pk AND p.pfile_pk I...
              ^ in /usr/share/fossology/lib/php/Db/Driver/Postgres.php on line 81
[2018-10-22 01:38:26] /usr/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column author.author_pk does not exist                                                                   LINE 5: WHERE public.author.author_pk = a.author_pk AND p.pfile_pk I...               ^ [] []
Something went wrong. Try running postinstall again!
*** Cleaning tables for new constraints ***
Removed 917 rows from tables with new constraints
PHP Warning:  pg_query(): Query failed: ERROR:  insert or update on table "clearing_decision_event" violates foreign key                                                                   constraint "clearing_decision_event_event_fk_fkey"
DETAIL:  Key (clearing_event_fk)=(2) is not present in table "clearing_event". in /usr/share/fossology/lib/php/Db/Driver/                                                                  Postgres.php on line 81
[2018-10-22 01:38:27] /usr/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  insert or update on table "clearing_de                                                                  cision_event" violates foreign key constraint "clearing_decision_event_event_fk_fkey" DETAIL:  Key (clearing_event_fk)=(2                                                                  ) is not present in table "clearing_event". [] []
PHP Fatal error:  Uncaught exception 'Fossology\Lib\Exception' with message 'error executing: ALTER TABLE "clearing_decis                                                                  ion_event" ADD CONSTRAINT "clearing_decision_event_event_fk_fkey" FOREIGN KEY ("clearing_event_fk") REFERENCES "clearing_                                                                  event" ("clearing_event_pk") ON UPDATE NO ACTION ON DELETE CASCADE;

ERROR:  insert or update on table "clearing_decision_event" violates foreign key constraint "clearing_decision_event_even                                                                  t_fk_fkey"
DETAIL:  Key (clearing_event_fk)=(2) is not present in table "clearing_event".' in /usr/share/fossology/lib/php/Db/DbMana                                                                  ger.php:140
Stack trace:
#0 /usr/share/fossology/lib/php/Db/DbManager.php(204): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "cl...                                                                  ')
#1 /usr/share/fossology/lib/php/libschema.php(70): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "cl...', 'fo_libsch                                                                  ema::a...')
#2 /usr/share/fossology/lib/php/libschema.php(465): fo_libschema->applyOrEchoOnce('ALTER TABLE "cl...', 'fo_libschema::a.                                                                  ..')
#3 /usr/share/fossology/lib/php/libschema.php(152): fo_libschema->appl in /usr/share/fossology/lib/php/Db/DbManager.php o                                                                  n line 140
dpkg: error processing package fossology-web (--install):
 subprocess installed post-installation script returned error exit status 255
Setting up fossology-wgetagent (3.4.0~rc1-1) ...
dpkg: dependency problems prevent configuration of fossology:
 fossology depends on fossology-web; however:
  Package fossology-web is not configured yet.
 fossology depends on fossology-scheduler; however:
  Package fossology-scheduler is not configured yet.

dpkg: error processing package fossology (--install):
 dependency problems - leaving unconfigured
Setting up fossology-buckets (3.4.0~rc1-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u7) ...
Errors were encountered while processing:
 fossology-ninka
 fossology-scheduler
 fossology-web
 fossology

```

**Comment by kohldampfer** [comment]
Seems to be similar to my reported problem: https://github.com/fossology/fossology/issues/1209
