### ISSUE TITLE
Migration database fails from 3.3.0 to 3.4.0

### ISSUE THREAD

**Issue by gwilga** [fossology/fossology#1256]
### Description

We try to migrate a 3.3.0 database into a 3.4.0. The process fails on SQL request. 
Our database had some add and removed project. Removed by the web UI (?mod=admin_upload_delete)
I wonder if this error is not related to https://github.com/fossology/fossology/issues/1090

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.
- Instanciate a 3.3.0 server
- Add projects
- Change some licenses
- Remove some projects
- Try an upgrade to 3.4.0 

### Versions

For 3.3.0: We use docker image to our needs: fossology/fossology:3.3.0
For our 3.4.0: we will use: quay.io/swi-infra/fossology:latest (which was build with 3.4.0 tag)

### Logs

```
Dec 19 16:09:47 FRILM-LX-ITE525 docker[30521]: Status: Image is up to date for quay.io/swi-infra/fossology:latest
Dec 19 16:09:47 FRILM-LX-ITE525 docker[30538]: Error response from daemon: network with name fossology already exists
Dec 19 16:09:47 FRILM-LX-ITE525 systemd[1]: Started Fossology service.
Dec 19 16:09:48 FRILM-LX-ITE525 docker[30553]: NOTE: using external DB on host fossology-postgres
Dec 19 16:09:48 FRILM-LX-ITE525 docker[30553]: *** update the database and license_ref table ***
Dec 19 16:09:48 FRILM-LX-ITE525 docker[30553]: Old release was 3.3.0
Dec 19 16:09:48 FRILM-LX-ITE525 docker[30553]: *** Cleaning tables for new constraints ***
Dec 19 16:09:50 FRILM-LX-ITE525 docker[30553]: Removed 0 rows from tables with new constraints
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: PHP Warning:  pg_query(): Query failed: ERROR:  insert or update on table "author" violates foreign key constraint "author_pfile_fk_fkey"
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: DETAIL:  Key (pfile_fk)=(241378) is not present in table "pfile". in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 81
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: [2018-12-19 15:10:12] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  insert or update on table "author" violates foreign key constraint "author_pfile_fk_fkey" DETAIL:  Key (pfile_fk)=(241378) is not present in table "pfile". [] []
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: PHP Fatal error:  Uncaught exception 'Fossology\Lib\Exception' with message 'error executing: ALTER TABLE "author" ADD CONSTRAINT "author_pfile_fk_fkey" FOREIGN KEY ("pfile_fk") REFERENCES "pfile" ("pfile_pk") ON UPDATE NO ACTION ON DELETE CASCADE;
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: ERROR:  insert or update on table "author" violates foreign key constraint "author_pfile_fk_fkey"
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: DETAIL:  Key (pfile_fk)=(241378) is not present in table "pfile".' in /usr/local/share/fossology/lib/php/Db/DbManager.php:140
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: Stack trace:
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: #0 /usr/local/share/fossology/lib/php/Db/DbManager.php(204): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "au...')
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: #1 /usr/local/share/fossology/lib/php/libschema.php(70): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "au...', 'fo_libschema::a...')
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: #2 /usr/local/share/fossology/lib/php/libschema.php(465): fo_libschema->applyOrEchoOnce('ALTER TABLE "au...', 'fo_libschema::a...')
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: #3 /usr/local/share/fossology/lib/php/libschema.php(152): fo_libschema->applyConstraints()
Dec 19 16:10:12 FRILM-LX-ITE525 docker[30553]: #4 /usr/local/lib/fossology/fossinit.php(176): fo_libschema->ap in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 140
Dec 19 16:10:13 FRILM-LX-ITE525 systemd[1]: fossology.service: Main process exited, code=exited, status=255/n/a
Dec 19 16:10:13 FRILM-LX-ITE525 docker[30743]: Error response from daemon: Cannot kill container: fossology: No such container: fossology
Dec 19 16:10:13 FRILM-LX-ITE525 systemd[1]: fossology.service: Control process exited, code=exited status=1
Dec 19 16:10:13 FRILM-LX-ITE525 systemd[1]: fossology.service: Unit entered failed state.
Dec 19 16:10:13 FRILM-LX-ITE525 systemd[1]: fossology.service: Failed with result 'exit-code'.
```

I have tried to use the **-Z** option of maintagent but this is not implemented yet. 
```
docker exec -it fossology /usr/local/share/fossology/maintagent/agent/maintagent -Z                                                                                                                                                     
NOTICE process.c.250: Remove orphaned files from the repository is not implemented yet
```

**Comment by mcjaeger** [comment]
(from discussion) seems like the author is not covered:
https://github.com/fossology/fossology/blob/eb37bc2236f53b194d3d9384d660668dc0fd8723/install/db/dbmigrate_3.3-3.4.php#L145

**Comment by GMishx** [comment]
This is a serious issue. We are working on it and will provide you with an update soon.

**Comment by gwilga** [comment]
Thanks, waiting for your patch.

**Comment by mcjaeger** [comment]
@gwilga many thanks for reporting it.

**Comment by mcjaeger** [comment]
please note that there is a docker image from Gaurav's fork which could be tested: https://github.com/fossology/fossology/pull/1261

**Comment by gwilga** [comment]
I see I have commented the wrong ticket, so:

I have tested you docker image and it seems to work correclty:
```
Dec 21 14:44:33 FRILM-LX-ITE525 docker[7085]: fix_constraints: Pulling from gmishx/fossology
Dec 21 14:44:33 FRILM-LX-ITE525 docker[7085]: Digest: sha256:a9d200d301f873178db29f1eb92ba157320c238fe1df271a90c603b79c9f230f
Dec 21 14:44:33 FRILM-LX-ITE525 docker[7085]: Status: Image is up to date for gmishx/fossology:fix_constraints
Dec 21 14:44:33 FRILM-LX-ITE525 docker[7113]: Error response from daemon: network with name fossology already exists
Dec 21 14:44:33 FRILM-LX-ITE525 systemd[1]: Started Fossology service.
Dec 21 14:44:34 FRILM-LX-ITE525 docker[7128]: NOTE: using external DB on host fossology-postgres
Dec 21 14:44:34 FRILM-LX-ITE525 docker[7128]: *** update the database and license_ref table ***
Dec 21 14:44:34 FRILM-LX-ITE525 docker[7128]: Old release was 3.3.0
Dec 21 14:44:34 FRILM-LX-ITE525 docker[7128]: *** Cleaning tables for new constraints ***
Dec 21 14:44:37 FRILM-LX-ITE525 docker[7128]: Removed 6798 rows from tables with new constraints
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]:   Applying database functions
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: DB schema has been updated for fossology.
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: Database schema update completed successfully.
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: Update reference licenses
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: FOSSology postinstall complete, but sure to complete the remaining
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]:   steps in the INSTALL instructions.
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: Fossology initialisation complete; Starting up...
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: Starting FOSSology job scheduler: fossology.
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: 2018-12-21 13:45:03 scheduler [29] :: NOTE: *****************************************************************
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: 2018-12-21 13:45:03 scheduler [29] :: NOTE: ***                FOSSology scheduler started                ***
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: 2018-12-21 13:45:03 scheduler [29] :: NOTE: ***        pid:      29                                       ***
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: 2018-12-21 13:45:03 scheduler [29] :: NOTE: ***        verbose:  3                                        ***
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: 2018-12-21 13:45:03 scheduler [29] :: NOTE: ***        config:   /usr/local/etc/fossology                 ***
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: 2018-12-21 13:45:03 scheduler [29] :: NOTE: *****************************************************************
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: 2018-12-21 13:45:03 scheduler [29] :: FATAL interface.c.525: [port:24693]: Error binding to address: Address already in use
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: 2018-12-21 13:45:03 scheduler [29] :: FATAL errno is: Address already in use
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: [Fri Dec 21 13:45:03.633166 2018] [mpm_prefork:notice] [pid 32] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
Dec 21 14:45:03 FRILM-LX-ITE525 docker[7128]: [Fri Dec 21 13:45:03.633210 2018] [core:notice] [pid 32] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```

However, when I want to check one file, I could not see the content (in the "Change concluded License" page), I got the message:
```
File contents are not available in the repository.

The File's Gold file is not available in the repository.
``` 

If I switch back to 3.3.0 (fossology/fossology:3.3.0), I can still see the content.
Should I do something special on "Gold's File" ?
