### ISSUE TITLE
rest api endpoints for jobs, uploads, report and folder are failing

### ISSUE THREAD

**Issue by ag4ums** [fossology/fossology#1287]
### Description
Rest API endpoint for report and folder are failing.

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

#### Apache logs

Logs generated under /var/log/apache2/error.log
```
[Fri Feb 08 16:16:11.463565 2019] [php7:notice] [pid 2995] [client 127.0.0.1:60616] [2019-02-08 16:16:11] default.ERROR: Error: Call to a member function scheduleAgent() on null in /usr/local/share/fossology/www/ui/api/Controllers/ReportController.php:95
Stack trace:
#0 [internal function]: Fossology\\UI\\Api\\Controllers\\ReportController->getReport(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)
#1 /usr/local/share/fossology/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)
#2 /usr/local/share/fossology/vendor/slim/slim/Slim/Route.php(356): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)
#3 /usr/local/share/fossology/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#4 /usr/local/share/fossology/vendor/slim/slim/Slim/Route.php(334): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#5 /usr/local/share/fossology/vendor/slim/slim/Slim/App.php(515): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#6 /usr/local/share/fossology/www/ui/api/Middlewares/RestAuthHelper.php(59): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#7 [internal function]: Fossology\\UI\\Api\\Middlewares\\RestAuthHelper->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))
#8 /usr/local/share/fossology/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Fossology\\UI\\Api\\Middlewares\\RestAuthHelper), Array)
#9 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))
#10 /usr/local/share/fossology/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))
#11 /usr/local/share/fossology/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#12 /usr/local/share/fossology/vendor/slim/slim/Slim/App.php(406): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#13 /usr/local/share/fossology/vendor/slim/slim/Slim/App.php(314): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#14 /usr/local/share/fossology/www/ui/api/index.php(157): Slim\\App->run()
#15 {main} [] []
[Fri Feb 08 16:17:39.163599 2019] [mpm_prefork:notice] [pid 1025] AH00171: Graceful restart requested, doing restart
```

**Comment by GMishx** [comment]
Other endpoints which are failing include `/jobs`, `/uploads`
