### ISSUE TITLE
pg_query(): Query failed: ERROR:  column "rf_fk" does not exist

### ISSUE THREAD

**Issue by abirw-zz** [fossology/fossology#1403]
### Description:

Trying to run fossology with an external database, getting that `Old release was 0` and attempting to `Migrate data from 2.1 to 2.2 in /usr/local/lib/fossology` but failing due to `Missing column clearing_decision.clearing_pk`.

### How to reproduce:

Have downloaded fossology db schema following steps on database wiki:
```
cd fossology-3.5.0
docker-compose up

docker exec -it fossology-350_db_1 pg_dump --create -f fossy.sql -s -U fossy -W fossology
docker cp fossology-350_db_1:/fossy.sql ~/fossy.sql
```
Then run postgres 9.6 in a docker container:
```
docker run -d --name fossdb -p 5432:5432 postgres:9.6
```
Copy the schema over:
```
docker cp fossy.sql fossdb:/fossy.sql
```
Recreate the database from schema:
```
docker exec -it fossdb bash
psql postgres -U postgres

create user fossy with password 'fossy';
create database fossology;
grant all privileges on database fossology to fossy;
\q

psql fossology < fossy.sql
psql postgres -U postgres
\connect fossology
```
Then go run fossology:
```
docker run -d --name fossy -it -e FOSSOLOGY_DB_HOST=172.17.0.2 -p 8081:80 fossology/fossology:latest
```
Produces the following output:
```
*** Running postinstall for common actions***
*** Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
*** Making sure needed dirs exist with right ownership/permissions ***
*** clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.
      We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.
      Admin > Dashboard will show you the last time vacuum and analyze have been run.
NOTE: using external DB on host 172.17.0.2
*** update the database and license_ref table ***
Old release was 0
  Applying database functions
DB schema has been updated for fossology.
Database schema update completed successfully.
fresh install, import licenseRef.json 
Migrate data from 2.1 to 2.2 in /usr/local/lib/fossology
Missing column clearing_decision.clearing_pk, you should update to version 2.6.2 before migration
Enter 'i' within 20 seconds to ignore this warning and run the risk of losing clearing decisions:
```
Enter i:
```
Adding link to real parent in uploadtree table
Rename license (using /usr/local/lib/fossology) for SPDX validity
Transform bulk licenses into bulk license sets...PHP Warning:  pg_query(): Query failed: ERROR:  column "rf_fk" does not exist
LINE 3:   SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bul...
                                ^
HINT:  There is a column named "rf_fk" in table "license_set_bulk", but it cannot be referenced from this part of the query. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
[2019-07-16 13:35:49] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "rf_fk" does not exist LINE 3:   SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bul...                                 ^ HINT:  There is a column named "rf_fk" in table "license_set_bulk", but it cannot be referenced from this part of the query. [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: 
  INSERT INTO license_set_bulk (lrb_fk, rf_fk, removing)
  SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bulk

ERROR:  column "rf_fk" does not exist
LINE 3:   SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bul...
                                ^
HINT:  There is a column named "rf_fk" in table "license_set_bulk", but it cannot be referenced from this part of the query. in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, '\n  INSERT INTO ...')
#1 /usr/local/lib/fossology/dbmigrate_bulk_license.php(29): Fossology\Lib\Db\DbManager->queryOnce('\n  INSERT INTO ...')
#2 /usr/local/lib/fossology/fossinit.php(318): require_once('/usr/local/lib/...')
#3 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
```
### Versions

Last commit id on master: 5cc1802 
lsb_release -a (on fossdb container): 
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

### Logs

Any logs (if any) generated in

#### FOSSology logs

Logs generated under /var/log/fossology/fossology.log

#### Apache logs

Logs generated under /var/log/apache2/error.log

#### Job logs

Logs generated under Geeky Scan Details (Job history => click on agent's job id)

**Comment by shaheemazmalmmd** [comment]
2.1 and 2.2 versions are not supported any more. i hope you are using a newer version.
