### ISSUE TITLE
External database version not recognised

### ISSUE THREAD

**Issue by abirw** [fossology/fossology#1404]
### Description

When loading the fossology docker image with an external database, it says 'Old release was 0' and begins trying to migrate from version 2.1 to 2.2. The actual database version should be 3.5 as it is simply recreated from a schema of the database used in fossology 3.5.0. As a result, the database has columns missing/renamed from version 2.1. I'm not sure how to fix this.

#### How to reproduce

`docker-compose up` in fossology-3.5.0. Then do a pg_dump of the database 'fossology' in the database container to get the schema. Open a new container running postgres. Use psql to recreate the database from the schema. Open a new fossology container with the postgres container as the database host. See what happens.

#### Screenshots

```
*** Running postinstall for common actions***
*** Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
*** Making sure needed dirs exist with right ownership/permissions ***
*** clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.
      We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.
      Admin > Dashboard will show you the last time vacuum and analyze have been run.
NOTE: using external DB on host 172.17.0.2
*** update the database and license_ref table ***
Old release was 0
  Applying database functions
DB schema has been updated for fossology.
Database schema update completed successfully.
fresh install, import licenseRef.json 
Migrate data from 2.1 to 2.2 in /usr/local/lib/fossology
Missing column clearing_decision.clearing_pk, you should update to version 2.6.2 before migration
Enter 'i' within 20 seconds to ignore this warning and run the risk of losing clearing decisions: i

Rename license (using /usr/local/lib/fossology) for SPDX validity
Transform bulk licenses into bulk license sets...PHP Warning:  pg_query(): Query failed: ERROR:  column "rf_fk" does not exist
LINE 3:   SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bul...
                                ^
HINT:  There is a column named "rf_fk" in table "license_set_bulk", but it cannot be referenced from this part of the query. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
[2019-07-16 13:35:49] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "rf_fk" does not exist LINE 3:   SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bul...                                 ^ HINT:  There is a column named "rf_fk" in table "license_set_bulk", but it cannot be referenced from this part of the query. [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: 
  INSERT INTO license_set_bulk (lrb_fk, rf_fk, removing)
  SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bulk

ERROR:  column "rf_fk" does not exist
LINE 3:   SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bul...
                                ^
HINT:  There is a column named "rf_fk" in table "license_set_bulk", but it cannot be referenced from this part of the query. in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, '\n  INSERT INTO ...')
#1 /usr/local/lib/fossology/dbmigrate_bulk_license.php(29): Fossology\Lib\Db\DbManager->queryOnce('\n  INSERT INTO ...')
#2 /usr/local/lib/fossology/fossinit.php(318): require_once('/usr/local/lib/...')
#3 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
```

**Comment by abirw** [comment]
I ended up editing the schema until all errors had gone (i.e. it was version 2.1). 

Now I am having issues only when using fossology in the gitlab CI:

- Firstly, `fossjobs --username "fossy" --password "fossy" -u` produces the output `# The following uploads are available (upload id: name)` followed by nothing, even though an upload has just been made with the upload_pk 2.
- Then when run in a docker container from my Mac's terminal, `docker exec fossy fo_nomos_license_list -u 2 --username "fossy" --password "fossy"` produces a list of files with their corresponding licences as expected. However, when the exact same sequence of steps is performed in a docker container in gitlab, the following output is produced:
```
did not find uploadTreeId in uploadtree_astring(442) "
#0 /usr/local/share/fossology/lib/php/Dao/UploadDao.php(94): Fossology\Lib\Dao\UploadDao->createItemTreeBounds(false, 'uploadtree_a') 
#1 /usr/local/lib/fossology/fo_nomos_license_list.php(145): Fossology\Lib\Dao\UploadDao->getItemTreeBounds(NULL, 'uploadtree_a') 
#2 /usr/local/lib/fossology/fo_nomos_license_list.php(171): GetLicenseList(NULL, '2', 0, '', 0) 
#3 /usr/local/lib/fossology/fo_wrapper(77): require('/usr/local/lib/...') 
#4 {main}"
``` 

It seems to me that fossology is treating the upload_pk as an uploadtree_pk? I'm not too sure about this but any help would be appreciated.
