### ISSUE TITLE
Install of Fossology 3.6.0 fails when configured with a database that isn't called "fossology"

### ISSUE THREAD

**Issue by jl431** [fossology/fossology#1543]
### Description
I'm attempting to install 3.6.0 but Fossology never starts up.
I'm using a Postgres database for state.
Fossology is running as a docker container.

#### How to reproduce
This doesn’t work:
```
docker network create mynet

docker run --name some-postgres \
-e POSTGRES_USER=fossology_dev \
-e POSTGRES_PASSWORD=pass \
-e POSTGRES_DB=anyotherdbname \
-e POSTGRES_INITDB_ARGS='-E SQL_ASCII' \
--network mynet \
-d postgres:9.6.0

docker run --name fossology \
-p 8081:80 \
--env FOSSOLOGY_DB_HOST=some-postgres \
--env FOSSOLOGY_DB_NAME=anyotherdbname \
--env FOSSOLOGY_DB_USER=fossology_dev \
--env FOSSOLOGY_DB_PASSWORD=pass \
--network mynet fossology/fossology:3.6.0
```
Error log:
```
Removed 0 rows from tables with new constraints
PHP Warning:  pg_query(): Query failed: ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
[2019-12-04 17:15:05] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "option_value" of relation "sysconfig" already exists [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "sysconfig" ADD COLUMN "option_value" character varying(40) DEFAULT NULL

ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "sy...')
#1 /usr/local/share/fossology/lib/php/libschema.php(299): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "sy...')
#2 /usr/local/share/fossology/lib/php/libschema.php(161): fo_libschema->applyTables()
#3 /usr/local/lib/fossology/fossinit.php(191): fo_libschema->applySchema('/usr/local/shar...', false, 'fossology', Array)
#4 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
```

Updating the database name from anyotherdbname to fossology works as expected:
```

docker stop some-postgres && docker rm some-postgres
docker stop fossology && docker rm fossology

docker network create mynet

docker run --name some-postgres \
-e POSTGRES_USER=fossology_dev \
-e POSTGRES_PASSWORD=pass \
-e POSTGRES_DB=fossology \
-e POSTGRES_INITDB_ARGS='-E SQL_ASCII' \
--network mynet \
-d postgres:9.6.0

docker run --name fossology \
-p 8081:80 \
--env FOSSOLOGY_DB_HOST=some-postgres \
--env FOSSOLOGY_DB_NAME=fossology \
--env FOSSOLOGY_DB_USER=fossology_dev \
--env FOSSOLOGY_DB_PASSWORD=pass \
--network mynet fossology/fossology:3.6.0
```
Output:
```

2019-12-04 17:17:13 scheduler [56] :: NOTE: ***                FOSSology scheduler started                ***
```

### Versions
* Dockerhub container: fossology/fossology:3.6.0
I've also verified this is still an issue in master branch, 3.4.0 and 3.5.0.
The issue was not present in 3.3.0 and the above recreation steps work fine there.

#### FOSSology logs

```
*** Running postinstall for common actions***
*** Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
*** Making sure needed dirs exist with right ownership/permissions ***
*** clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.
      We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.
      Admin > Dashboard will show you the last time vacuum and analyze have been run.
NOTE: using external DB on host some-postgres
*** update the database and license_ref table ***
Old release was 0
*** Cleaning tables for new constraints ***
Table author or agent does not exists, not cleaning!
Table author or pfile does not exists, not cleaning!
Table bucket_container or bucket_def does not exists, not cleaning!
Table bucket_file or bucket_def does not exists, not cleaning!
Table bucket_file or pfile does not exists, not cleaning!
Table copyright or agent does not exists, not cleaning!
Table copyright_decision or pfile does not exists, not cleaning!
Table ecc or agent does not exists, not cleaning!
Table ecc or pfile does not exists, not cleaning!
Table ecc_decision or pfile does not exists, not cleaning!
Table highlight_keyword or pfile does not exists, not cleaning!
Table keyword or agent does not exists, not cleaning!
Table keyword or pfile does not exists, not cleaning!
Table keyword_decision or pfile does not exists, not cleaning!
Table pkg_deb_req or pkg_deb does not exists, not cleaning!
Table pkg_rpm_req or pkg_rpm does not exists, not cleaning!
Table report_cache or upload does not exists, not cleaning!
Table report_info or upload does not exists, not cleaning!
Table reportgen or upload does not exists, not cleaning!
Table upload or pfile does not exists, not cleaning!
Table upload_clearing_license or upload does not exists, not cleaning!
Table obligation_ref does not exists, not cleaning!
Table report_info does not exists, not cleaning!
Table obligation_ref does not exists, not cleaning!
Table group_user_member does not exists, not cleaning!
Removed 0 rows from tables with new constraints
PHP Warning:  pg_query(): Query failed: ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
[2019-12-04 17:15:05] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "option_value" of relation "sysconfig" already exists [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "sysconfig" ADD COLUMN "option_value" character varying(40) DEFAULT NULL

ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "sy...')
#1 /usr/local/share/fossology/lib/php/libschema.php(299): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "sy...')
#2 /usr/local/share/fossology/lib/php/libschema.php(161): fo_libschema->applyTables()
#3 /usr/local/lib/fossology/fossinit.php(191): fo_libschema->applySchema('/usr/local/shar...', false, 'fossology', Array)
#4 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
```

**Comment by jl431** [comment]
Whilst attempting to generate simpler recreation steps, I came across a seemingly similar issue:
```
docker network create mynet
docker run --name some-postgres -e POSTGRES_USER=fossology -e POSTGRES_PASSWORD=pass -e POSTGRES_DB=fossology -e POSTGRES_INITDB_ARGS='-E SQL_ASCII' --network mynet -d postgres
docker run -p 8081:80 --env FOSSOLOGY_DB_HOST=some-postgres --env FOSSOLOGY_DB_NAME=fossology --env FOSSOLOGY_DB_USER=fossology --env FOSSOLOGY_DB_PASSWORD=pass --network mynet fossology/fossology:3.6.0 
```
Error log:
```
*** Running postinstall for common actions***
*** Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
*** Making sure needed dirs exist with right ownership/permissions ***
*** clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.
      We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.
      Admin > Dashboard will show you the last time vacuum and analyze have been run.
NOTE: using external DB on host some-postgres
*** update the database and license_ref table ***
PHP Warning:  pg_prepare(): Query failed: ERROR:  column attrdef.adsrc does not exist
LINE 7:         attrdef.adsrc AS default,
                ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 60
[2019-12-04 13:45:02] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column attrdef.adsrc does not exist LINE 7:         attrdef.adsrc AS default,                 ^ [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: SELECT class.relname AS table,
        attr.attnum AS ordinal,
        attr.attname AS column_name,
        type.typname AS type,
        attr.atttypmod-4 AS modifier,
        attr.attnotnull AS notnull,
        attrdef.adsrc AS default,
        col_description(attr.attrelid, attr.attnum) AS description
      FROM pg_class AS class
      INNER JOIN pg_attribute AS attr ON attr.attrelid = class.oid AND attr.attnum > 0
      INNER JOIN pg_type AS type ON attr.atttypid = type.oid
      INNER JOIN information_schema.tables AS tab ON class.relname = tab.table_name
        AND tab.table_type = 'BASE TABLE'
        AND tab.table_schema = 'public'
      LEFT OUTER JOIN pg_attrdef AS attrdef ON adrelid = attrelid AND adnum = attnum
      ORDER BY class.relname,attr.attnum -- fo_libschema::addTables

ERROR:  column attrdef.adsrc does not exist
LINE 7:         attrdef.adsrc AS default,
                ^ in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack tr in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
```

**Comment by jl431** [comment]
I've attempted debugging the code.
Custom debug: ALTER TABLE "sysconfig" ADD COLUMN "option_value" character varying(40) DEFAULT NULL
PHP Warning:  pg_query(): Query failed: ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
[2019-12-04 20:53:11] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "option_value" of relation "sysconfig" already exists [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "sysconfig" ADD COLUMN "option_value" character varying(40) DEFAULT NULL
ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "sy...')
#1 /usr/local/share/fossology/lib/php/libschema.php(304): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "sy...')
#2 /usr/local/share/fossology/lib/php/libschema.php(161): fo_libschema->applyTables()
#3 /usr/local/lib/fossology/fossinit.php(195): fo_libschema->applySchema('/usr/local/shar...', false, 'fossology', Array)
#4 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144

I've patched the core-schema.dat file locally and it appears to work.
Would this make sense for a fix? - Adding IF NOT EXISTS to the creation query.
Current:
 $Schema["TABLE"]["sysconfig"]["option_value"]["ADD"] = "ALTER TABLE \"sysconfig\" ADD COLUMN \"option_value\" character varying(40) DEFAULT NULL";

Working: 
 $Schema["TABLE"]["sysconfig"]["option_value"]["ADD"] = "ALTER TABLE \"sysconfig\" ADD COLUMN IF NOT EXISTS \"option_value\" character varying(40) DEFAULT NULL";

**Comment by bharathkumar522** [comment]
Hi @deveaud-m,
        I am running fossology from Master source (i.e without docker). I want to configure PostgreSQL externally. Please share few inputs

**Comment by GMishx** [comment]
Hello @bharathkumar522,
There actually is a small catch (or bug) that the server running FOSSology should have a running PostgreSQL server, no matter where you are hosting your actual DB.

But, if you want to use external DB, you can edit the Db.conf file and update the parameters for it. Every script on FOSSology refers to the same file and thus every action done while installing or using FOSSology will happen as per the configuration.

If you did a source install or using docker, the file will be located as `/usr/local/etc/fossology/Db.conf`.
If you did a deb package install, the file will be located as `/etc/fossology/Db.conf`.

**Comment by bharathkumar522** [comment]
Hello @GMishx ,
       I am running from deb package and the file path(/usr/local/etc/fossology/Db.conf)
| Existing | Updated|
| --- | --- |
| dbname=fossology; |dbname= testing; |
  host=localhost; | host=localhost; |
  |user=fossy; 	|user=user_1 ;|
|password=fossy;	|password=test123 ;|
 |client_encoding=utf8; | client_encoding=utf8 ;|

After the above changes i restarted the Apache server and open the web browser 
1. Page is not loading
2. Verified Apache log file
![image](https://user-images.githubusercontent.com/5959431/87010115-b8c6e180-c1e3-11ea-89da-f61440d49feb.png)

Please let me know is there any other place to change

**Comment by GMishx** [comment]
Can you please try checking the apache error log?

**Comment by bharathkumar522** [comment]
> Can you please try checking the apache error log?

In point 2 I attached a screenshot which generated last after changing the DB.

**Comment by GMishx** [comment]
That looks more like the access log than the error log. Can you please check on `/var/log/apache2/error.log`?

**Comment by bharathkumar522** [comment]
Error msg:

[Thu Jul 09 13:05:26.632794 2020] [php7:error] [pid 4072] [client 127.0.0.1:46128] PHP Fatal error:  Uncaught Fossology\\Lib\\Exception: error executing: UPDATE users SET user_seed = $1 WHERE user_seed IS NULL; -- updateUserTable.randomizeEmptySeeds\n\nERROR:  relation "users" does not exist\nLINE 1: UPDATE users SET user_seed = $1 WHERE user_seed IS NULL;\n               ^ in /usr/local/share/fossology/lib/php/Db/DbManager.php:144\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Db/ModernDbManager.php(49): Fossology\\Lib\\Db\\DbManager->checkResult(false, 'UPDATE users SE...')\n#1 /usr/local/share/fossology/lib/php/Db/DbManager.php(161): Fossology\\Lib\\Db\\ModernDbManager->prepare('updateUserTable...', 'UPDATE users SE...')\n#2 /usr/local/share/fossology/lib/php/Dao/UserDao.php(197): Fossology\\Lib\\Db\\DbManager->getSingleRow('UPDATE users SE...', Array, 'updateUserTable...')\n#3 /usr/local/share/fossology/www/ui/core-auth.php(73): Fossology\\Lib\\Dao\\UserDao->updateUserTable()\n#4 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(484): core_auth->Install()\n#5 /usr/local/share/fossology/lib/php/common-plugin.php(243): in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
[Thu Jul 09 13:05:33.500694 2020] [php7:warn] [pid 4202] [client 127.0.0.1:46132] PHP Warning:  pg_prepare(): Query failed: ERROR:  relation &quot;users&quot; does not exist\nLINE 1: UPDATE users SET user_seed = $1 WHERE user_seed IS NULL;\n               ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 60
[Thu Jul 09 13:05:33.500797 2020] [php7:notice] [pid 4202] [client 127.0.0.1:46132] [2020-07-09 13:05:33] default.CRITICAL: ERROR:  relation "users" does not exist LINE 1: UPDATE users SET user_seed = $1 WHERE user_seed IS NULL;                ^ [] []


New DB created:
![image](https://user-images.githubusercontent.com/5959431/87019690-88397480-c1f0-11ea-9a5f-47d4cf4ad824.png)

**Comment by GMishx** [comment]
After changing the database, you need to run `/usr/local/lib/fossology/fo-postinstall` to setup the database tables.

**Comment by bharathkumar522** [comment]
Thanks a lot, @GMishx after running the above command it worked finally.
