### ISSUE TITLE
Fossology scheduler container dies after restarting it 1600 times

### ISSUE THREAD

**Issue by jb68** [fossology/fossology#1701]
### Description
Fossology scheduler dies after restarting it 1600 times 
This is related to https://bytes.com/topic/postgresql/answers/422107-error-tables-can-have-most-1600-columns

#### How to reproduce
Use docker fossology and restart scheduler 1600 times +
After that scheduler will stop re starting. It seems that at every restart it apply the upgrade instead of checking the version and exit iv version is right.

### Versions
3.7 docker

#### FOSSology logs
```
Apr 23 22:03:41 AZUSW2-CTO-CVM docker[114276]: fossology-scheduler
Apr 23 22:03:41 AZUSW2-CTO-CVM systemd[1]: Starting Fossology service...
Apr 23 22:03:41 AZUSW2-CTO-CVM systemd[1]: Stopped Fossology service.
Apr 23 22:03:41 AZUSW2-CTO-CVM systemd[1]: fossology-scheduler.service: Scheduled restart job, restart counter is at 19.
Apr 23 22:03:41 AZUSW2-CTO-CVM systemd[1]: fossology-scheduler.service: Service RestartSec=10s expired, scheduling restart.
Apr 23 22:03:31 AZUSW2-CTO-CVM systemd[1]: fossology-scheduler.service: Failed with result 'exit-code'.
Apr 23 22:03:31 AZUSW2-CTO-CVM systemd[1]: fossology-scheduler.service: Main process exited, code=exited, status=255/EXCEPTION
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]:   thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: #4 {main}
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: #3 /usr/local/lib/fossology/fossinit.php(191): fo_libschema->applySchema('/usr/local/shar...', false, 'fossology', Array)
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: #2 /usr/local/share/fossology/lib/php/libschema.php(161): fo_libschema->applyTables()
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: #1 /usr/local/share/fossology/lib/php/libschema.php(299): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "re...')
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: #0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "re...')
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: Stack trace:
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: ERROR:  tables can have at most 1600 columns in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "report_info" ADD COLUMN "ri_ga_risk" text DEFAULT 'NA'
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: [2020-04-23 22:03:30] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  tables can have at most 1600 columns [] []
Apr 23 22:03:30 AZUSW2-CTO-CVM docker[114046]: PHP Warning:  pg_query(): Query failed: ERROR:  tables can have at most 1600 columns in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
Apr 23 22:03:15 AZUSW2-CTO-CVM docker[114046]: Old release was 3.7.0
```

**Comment by GMishx** [comment]
That is quite strange. The script should remove additional columns from the table.

I request you to provide few additional information:
1. Which Postgres server you are using?
2. Output of following SQL:
```sql
SELECT
  table_name AS table, ordinal_position AS ordinal, column_name,
  udt_name AS type, character_maximum_length AS modifier,
  CASE is_nullable WHEN 'YES' THEN false WHEN 'NO' THEN true END AS notnull,
  column_default AS default,
  col_description(table_name::regclass, ordinal_position) AS description
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'report_info'
ORDER BY table_name, ordinal_position;
```

**Comment by mcjaeger** [comment]
@jb68 hello, would you mind to have a conversation with us. we are not sure under which conditions you expereince your observation. At the same time we would like to release 3.8 soon.

Would you be Ok to reach out to us on slack to have a conversation?
 https://join.slack.com/t/fossology/shared_invite/enQtNzI0OTEzMTk0MjYzLTYyZWQxNDc0N2JiZGU2YmI3YmI1NjE4NDVjOGYxMTVjNGY3Y2MzZmM1OGZmMWI5NTRjMzJlNjExZGU2N2I5NGY

**Comment by jb68** [comment]
First I have a workaround by dumping and reloading the db: 
```bash
pg_dump -U fossy fossology > fossology.pgsql
createdb -U fossy --owner fossy fossology
psql -U fossy fossology < fossology.pgsql
```
This should reset the counter.

@GMishx 
1. I am using `docker pull postgres:10`
2. This is after applying the workaround.
```csv
"table","ordinal","column_name","type","modifier","notnull","default","description"
"report_info",1,"ri_pk","int4","",True,"nextval('report_info_pk_seq'::regclass)",""
"report_info",2,"upload_fk","int4","",True,"",""
"report_info",3,"ri_ga_checkbox_selection","text","",False,"",""
"report_info",4,"ri_spdx_selection","text","",False,"",""
"report_info",5,"ri_excluded_obligations","json","",False,"",""
"report_info",28,"ri_reviewed","text","",True,"'NA'::text",""
"report_info",29,"ri_footer","text","",True,"'Your Organization'::text",""
"report_info",30,"ri_report_rel","text","",True,"'NA'::text",""
"report_info",31,"ri_community","text","",True,"'NA'::text",""
"report_info",32,"ri_component","text","",True,"'NA'::text",""
"report_info",33,"ri_version","text","",True,"'NA'::text",""
"report_info",34,"ri_release_date","text","",True,"'NA'::text",""
"report_info",35,"ri_sw360_link","text","",True,"'NA'::text",""
"report_info",36,"ri_general_assesment","text","",True,"'NA'::text",""
"report_info",37,"ri_ga_additional","text","",True,"'NA'::text",""
"report_info",38,"ri_ga_risk","text","",True,"'NA'::text",""
```
3. These are the logs when restarting scheduler after dumping the DB.
```
Apr 24 16:14:05 AZUSW2-CTO-CVM-klocwk docker[15035]: 2020-04-24 16:14:05 scheduler [1] :: NOTE: *******************************************************>
Apr 24 16:14:05 AZUSW2-CTO-CVM-klocwk docker[15035]: 2020-04-24 16:14:05 scheduler [1] :: NOTE: ***        config:   /usr/local/etc/fossology          >
Apr 24 16:14:05 AZUSW2-CTO-CVM-klocwk docker[15035]: 2020-04-24 16:14:05 scheduler [1] :: NOTE: ***        verbose:  3                                 >
Apr 24 16:14:05 AZUSW2-CTO-CVM-klocwk docker[15035]: 2020-04-24 16:14:05 scheduler [1] :: NOTE: ***        pid:      1                                 >
Apr 24 16:14:05 AZUSW2-CTO-CVM-klocwk docker[15035]: 2020-04-24 16:14:05 scheduler [1] :: NOTE: ***                FOSSology scheduler started         >
Apr 24 16:14:05 AZUSW2-CTO-CVM-klocwk docker[15035]: 2020-04-24 16:14:05 scheduler [1] :: NOTE: *******************************************************>
Apr 24 16:14:05 AZUSW2-CTO-CVM-klocwk docker[15035]: Fossology initialisation complete; Starting up...
Apr 24 16:14:05 AZUSW2-CTO-CVM-klocwk docker[15035]:   steps in the INSTALL instructions.
Apr 24 16:14:05 AZUSW2-CTO-CVM-klocwk docker[15035]: FOSSology postinstall complete, but sure to complete the remaining
Apr 24 16:14:02 AZUSW2-CTO-CVM-klocwk docker[15035]: * 1 pfile records updated **** Updated sha256 of 1/1 records of pfile ***
Apr 24 16:14:02 AZUSW2-CTO-CVM-klocwk docker[15035]: *** Updating the sha256 values of pfiles ***
Apr 24 16:14:02 AZUSW2-CTO-CVM-klocwk docker[15035]: *** Calculation of SHA256 for pfiles will require approx 0 hrs 0 mins. ***
Apr 24 16:14:00 AZUSW2-CTO-CVM-klocwk docker[15035]: Update reference licenses
Apr 24 16:14:00 AZUSW2-CTO-CVM-klocwk docker[15035]: Database schema update completed successfully.
Apr 24 16:14:00 AZUSW2-CTO-CVM-klocwk docker[15035]: DB schema has been updated for fossology.
Apr 24 16:14:00 AZUSW2-CTO-CVM-klocwk docker[15035]:   Applying database functions
Apr 24 16:13:59 AZUSW2-CTO-CVM-klocwk docker[15035]: Old release was 3.7.0
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: *** update the database and license_ref table ***
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: NOTE: using external DB on host fossology-postgres
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]:       Admin > Dashboard will show you the last time vacuum and analyze have been run.
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]:       We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons,>
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance>
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: NOTE: Repository already exists at /srv/fossology/repository
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: *** clearing file cache ***
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: *** Making sure needed dirs exist with right ownership/permissions ***
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: NOTE: user 'fossy' already exists, good.
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: NOTE: group 'fossy' already exists, good.
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: *** Creating user and group ***
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: *** Running postinstall for common actions***
Apr 24 16:13:56 AZUSW2-CTO-CVM-klocwk systemd[1]: Started Fossology service.
```
Note:
```
 Applying database functions
Apr 24 16:13:59 AZUSW2-CTO-CVM-klocwk docker[15035]: Old release was 3.7.0
Apr 24 16:13:58 AZUSW2-CTO-CVM-klocwk docker[15035]: *** update the database and license_ref table ***
```
I am not sure here but it should figure out it is current release, and say something like release current

**Comment by GMishx** [comment]
I just did a small check on my machine and found that the FOSSology was recreating the columns in `report_info` table (the `ordinal` value for the columns were changing). Later from the [Postgres docs](https://www.postgresql.org/docs/current/limits.html), I found that
> Columns that have been dropped from the table also contribute to the maximum column limit. Moreover, although the dropped column values for newly created tuples are internally marked as null in the tuple's null bitmap, the null bitmap also occupies space.

That means, even though the table does not have 1600 columns, if the columns were dropped and created 1600 times, it will have similar effect like having 1600 columns.

The PR #1705 updates the default `core-schema.dat` to match the current schema reducing the number of column changes in DB.

However, the ordinal value of the columns will keep increasing in case of change in schema but it can't be handled programmatically. To reset the counter, the entire table needs to be recreated (as done by you @jb68 using the `pg_dump`).

**Comment by jb68** [comment]
We've been hit by this bug again. 
We ramped our setup a bit, to start a scheduler on the host that we do the build so in this way we cut on upload files + we delegate the heavy work on a different host. 
Now the table with issue is license_ref

**Comment by GMishx** [comment]
Hello @jb68 I think PR #1705 already solved the issue for most of the tables. Will do a review of the schema again and update here.
