### ISSUE TITLE
Show message in case of empty timestamp

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#1741]
#### How to reproduce

* Reset master to any commit before 00a68a13d180b24043173d95c3a1e0401953f245 . 
* Clean browser session.
* Install fossology. Upload a package and goto showjobs.
* Now Pull the changes of master and install them. Reload same page.
* Page goes blank without showing any error in UI.

### Versions

* Latest commit ion master.

### Logs

```
[Wed Jun 10 19:08:08.783715 2020] [php7:notice] [pid 26485] [client 10.0.2.2:63905] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/local/share/fossology/lib/php/common-ui.php:303\nStack trace:\n#0 /usr/local/share/fossology/lib/php/common-ui.php(303): DateTimeZone->__construct('')\n#1 /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php(233): Convert2BrowserTime(NULL)\n#2 /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php(419): Fossology\\UI\\Ajax\\AjaxShowJobs->getShowJobsForEachJob(Array)\n#3 /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php(446): Fossology\\UI\\Ajax\\AjaxShowJobs->getJobs(-1)\n#4 /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php(432): Fossology\\UI\\Ajax\\AjaxShowJobs->jsonContent()\n#5 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(381): Fossology\\UI\\Ajax\\AjaxShowJobs->Output()\n#6 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(465): FO_Plugin->getResponse()\n#7 /usr/local/share/fossology/www/ui/index.php(64): FO_Plugin->execute()\n#8 {main}\n  thrown in /usr/local/share/fossology/lib/php/common-ui.php on line 303, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453518 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP Notice:  Undefined index: timezone in /usr/local/share/fossology/lib/php/common-ui.php on line 300, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453542 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP Stack trace:, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453546 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453549 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP   2. Fossology\\UI\\Ajax\\AjaxShowJobs->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453551 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP   3. Fossology\\UI\\Ajax\\AjaxShowJobs->getResponse() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:465, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453554 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP   4. Fossology\\UI\\Ajax\\AjaxShowJobs->Output() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:381, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453563 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP   5. Fossology\\UI\\Ajax\\AjaxShowJobs->jsonContent() /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php:432, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453566 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP   6. Fossology\\UI\\Ajax\\AjaxShowJobs->getJobs() /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php:446, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453568 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP   7. Fossology\\UI\\Ajax\\AjaxShowJobs->getShowJobsForEachJob() /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php:419, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453571 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP   8. Convert2BrowserTime() /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php:233, referer: http://localhost:2211/repo/?mod=showjobs
[Wed Jun 10 19:08:24.453666 2020] [php7:notice] [pid 26502] [client 10.0.2.2:63917] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/local/share/fossology/lib/php/common-ui.php:303\nStack trace:\n#0 /usr/local/share/fossology/lib/php/common-ui.php(303): DateTimeZone->__construct('')\n#1 /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php(233): Convert2BrowserTime(NULL)\n#2 /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php(419): Fossology\\UI\\Ajax\\AjaxShowJobs->getShowJobsForEachJob(Array)\n#3 /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php(446): Fossology\\UI\\Ajax\\AjaxShowJobs->getJobs(-1)\n#4 /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php(432): Fossology\\UI\\Ajax\\AjaxShowJobs->jsonContent()\n#5 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(381): Fossology\\UI\\Ajax\\AjaxShowJobs->Output()\n#6 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(465): FO_Plugin->getResponse()\n#7 /usr/local/share/fossology/www/ui/index.php(64): FO_Plugin->execute()\n#8 {main}\n  thrown in /usr/local/share/fossology/lib/php/common-ui.php on line 303, referer: http://localhost:2211/repo/?mod=showjobs
```

**Comment by GMishx** [comment]
One solution would be to check if session has `timezone`. If not, then use the `$server_timezone`

https://github.com/fossology/fossology/blob/d9f6f6753ce5e4b11668375dfe039a8871b3b499/src/lib/php/common-ui.php#L300-L301

**Comment by shaheemazmalmmd** [comment]
Yes i have resolved it by logging out and login again. But i think it would be better to show a message. if time zone is empty.

**Comment by DineshDevarajan** [comment]
@GMishx 

During user login , if the timezone is empty or unknown it is set to server timezone

https://github.com/fossology/fossology/blob/00a68a13d180b24043173d95c3a1e0401953f245/src/www/ui/core-auth.php#L206-L208

**Comment by GMishx** [comment]
> @GMishx 
> 
> During user login , if the timezone is empty or unknown it is set to server timezone
> 
> https://github.com/fossology/fossology/blob/00a68a13d180b24043173d95c3a1e0401953f245/src/www/ui/core-auth.php#L206-L208
> 

Yes @DineshDevarajan , but the issue occurs when you already have a running session and the server updates (with is extremely rare but possible). In that case you'll not have timezone set in the session variables.
