### ISSUE TITLE
Reuser errors after update to 3.8.1

### ISSUE THREAD

**Issue by jb68** [fossology/fossology#1763]
### Description

I am getting some errors after updating to 3.8.1 from 3.7. Some reuse jobs are failing but not all. 

### Versions

* Last commit id on master: 3.8.1
* Operating System (lsb_release -a): built using official docker file

#### Job logs

```
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "diff: missing operand after '/srv/fossology/repository/localhost/files/80/0f/06/800f06205dad07f772c662ead1acec1564e3fadc.ed1cd896570b3bcee72ca30d557c7de1.241341'"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "diff: Try 'diff --help' for more information."
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "0"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "PHP Warning:  pg_execute(): Query failed: ERROR:  insert or update on table "clearing_decision" violates foreign key constraint "clearing_decision_pfile_fk_fkey""
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "DETAIL:  Key (pfile_fk)=(0) is not present in table "pfile". in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 70"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "[2020-07-13 09:01:07] default.CRITICAL: ERROR:  insert or update on table "clearing_decision" violates foreign key constraint "clearing_decision_pfile_fk_fkey" DETAIL:  Key (pfile_fk)=(0) is not present in table "pfile". [] []"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "Caught exception while processing uploadId=1674: error executing: Fossology\Lib\Dao\ClearingDao::createDecisionFromEvents: "
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "INSERT INTO clearing_decision ("
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  uploadtree_fk,"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  pfile_fk,"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  user_fk,"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  group_fk,"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  decision_type,"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  scope"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: ") VALUES ("
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  $1,"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  (SELECT pfile_fk FROM uploadtree WHERE uploadtree_pk=$1),"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  $2,"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  $3,"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  $4,"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "  $5) RETURNING clearing_decision_pk"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "   -- -- Array"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "("
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "    [0] => 49627221"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "    [1] => 3"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "    [2] => 3"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "    [3] => 5"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "    [4] => 0"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: ")"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "ERROR:  insert or update on table "clearing_decision" violates foreign key constraint "clearing_decision_pfile_fk_fkey""
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "DETAIL:  Key (pfile_fk)=(0) is not present in table "pfile".#0 /usr/local/share/fossology/lib/php/Db/ModernDbManager.php(68): Fossology\Lib\Db\DbManager->checkResult(false, 'Fossology\\Lib\\D...')"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#1 /usr/local/share/fossology/lib/php/Dao/ClearingDao.php(359): Fossology\Lib\Db\ModernDbManager->execute('Fossology\\Lib\\D...', Array)"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#2 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(316): Fossology\Lib\Dao\ClearingDao->createDecisionFromEvents('49627221', '3', '3', 5, 0, Array)"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#3 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(261): Fossology\Reuser\ReuserAgent->createCopyOfClearingDecision('49627221', '3', '3', Object(Fossology\Lib\Data\ClearingDecision))"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#4 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(237): Fossology\Reuser\ReuserAgent->copyClearingDecisionIfDifferenceIsSmall('/srv/fossology/...', NULL, Object(Fossology\Lib\Data\ClearingDecision), '49627221')"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#5 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(109): Fossology\Reuser\ReuserAgent->processEnhancedUploadReuse(Object(Fossology\Lib\Data\Tree\ItemTreeBounds), Object(Fossology\Lib\Data\Tree\ItemTreeBounds), '3')"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#6 /usr/local/share/fossology/lib/php/Agent/Agent.php(338): Fossology\Reuser\ReuserAgent->processUploadId(1674)"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#7 /usr/local/share/fossology/reuser/agent/reuser.php(59): Fossology\Lib\Agent\Agent->run_scheduler_event_loop()"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#8 /usr/local/lib/fossology/fo_wrapper(77): require('/usr/local/shar...')"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#9 {main}agent failed on uploadId=1674#0  Fossology\Lib\Agent\Agent->bail() called at [/usr/local/share/fossology/lib/php/Agent/Agent.php:349]"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#1  Fossology\Lib\Agent\Agent->run_scheduler_event_loop() called at [/usr/local/share/fossology/reuser/agent/reuser.php:59]"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: "#2  require(/usr/local/share/fossology/reuser/agent/reuser.php) called at [/usr/local/lib/fossology/fo_wrapper:77]"
2020-07-13 09:01:07 reuser [0] :: JOB[43618].reuser[88425.localhost]: agent failed with error code 1
```
Another log:
```
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "diff: missing operand after '/srv/fossology/repository/localhost/files/80/0f/06/800f06205dad07f772c662ead1acec1564e3fadc.ed1cd896570b3bcee72ca30d557c7de1.241341'"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "diff: Try 'diff --help' for more information."
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "0"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "PHP Warning:  pg_execute(): Query failed: ERROR:  insert or update on table "clearing_decision" violates foreign key constraint "clearing_decision_pfile_fk_fkey""
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "DETAIL:  Key (pfile_fk)=(0) is not present in table "pfile". in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 70"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "[2020-07-13 09:01:07] default.CRITICAL: ERROR:  insert or update on table "clearing_decision" violates foreign key constraint "clearing_decision_pfile_fk_fkey" DETAIL:  Key (pfile_fk)=(0) is not present in table "pfile". [] []"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "Caught exception while processing uploadId=1674: error executing: Fossology\Lib\Dao\ClearingDao::createDecisionFromEvents: "
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "INSERT INTO clearing_decision ("
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  uploadtree_fk,"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  pfile_fk,"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  user_fk,"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  group_fk,"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  decision_type,"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  scope"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: ") VALUES ("
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  $1,"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  (SELECT pfile_fk FROM uploadtree WHERE uploadtree_pk=$1),"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  $2,"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  $3,"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  $4,"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "  $5) RETURNING clearing_decision_pk"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "   -- -- Array"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "("
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "    [0] => 49627221"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "    [1] => 3"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "    [2] => 3"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "    [3] => 5"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "    [4] => 0"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: ")"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "ERROR:  insert or update on table "clearing_decision" violates foreign key constraint "clearing_decision_pfile_fk_fkey""
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "DETAIL:  Key (pfile_fk)=(0) is not present in table "pfile".#0 /usr/local/share/fossology/lib/php/Db/ModernDbManager.php(68): Fossology\Lib\Db\DbManager->checkResult(false, 'Fossology\\Lib\\D...')"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#1 /usr/local/share/fossology/lib/php/Dao/ClearingDao.php(359): Fossology\Lib\Db\ModernDbManager->execute('Fossology\\Lib\\D...', Array)"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#2 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(316): Fossology\Lib\Dao\ClearingDao->createDecisionFromEvents('49627221', '3', '3', 5, 0, Array)"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#3 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(261): Fossology\Reuser\ReuserAgent->createCopyOfClearingDecision('49627221', '3', '3', Object(Fossology\Lib\Data\ClearingDecision))"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#4 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(237): Fossology\Reuser\ReuserAgent->copyClearingDecisionIfDifferenceIsSmall('/srv/fossology/...', NULL, Object(Fossology\Lib\Data\ClearingDecision), '49627221')"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#5 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(109): Fossology\Reuser\ReuserAgent->processEnhancedUploadReuse(Object(Fossology\Lib\Data\Tree\ItemTreeBounds), Object(Fossology\Lib\Data\Tree\ItemTreeBounds), '3')"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#6 /usr/local/share/fossology/lib/php/Agent/Agent.php(338): Fossology\Reuser\ReuserAgent->processUploadId(1674)"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#7 /usr/local/share/fossology/reuser/agent/reuser.php(59): Fossology\Lib\Agent\Agent->run_scheduler_event_loop()"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#8 /usr/local/lib/fossology/fo_wrapper(77): require('/usr/local/shar...')"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#9 {main}agent failed on uploadId=1674#0  Fossology\Lib\Agent\Agent->bail() called at [/usr/local/share/fossology/lib/php/Agent/Agent.php:349]"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#1  Fossology\Lib\Agent\Agent->run_scheduler_event_loop() called at [/usr/local/share/fossology/reuser/agent/reuser.php:59]"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: "#2  require(/usr/local/share/fossology/reuser/agent/reuser.php) called at [/usr/local/lib/fossology/fo_wrapper:77]"
2020-07-13 09:01:07 reuser [0] :: JOB[43616].reuser[88416.localhost]: agent failed with error code 1
```

Any ideas what should I look at?

**Comment by GMishx** [comment]
Looks like some of the files are missing from your machine. Like from your logs, `uploadtree_pk` = `49627221` is missing it's pfile.
Or this is a directory?

Will it be possible for you to share the details from DB about that `uploadtree_pk` ?

```sql
SELECT * FROM uploadtree INNER JOIN pfile on pfile_pk = pfile_fk WHERE uploadtree_pk = 49627221;
```

**Comment by GMishx** [comment]
Hello @jb68,
What I can understand here, you might have deleted some older upload and somehow the uploadtree id got assigned to a folder now.

The issue should be fixed by #1752.

For your system running on 3.8.1, you can try to manually delete the `clearing_decision` as:
```sql
DELETE FROM clearing_decision WHERE uploadtree_fk = 49627221;
```

**Comment by jb68** [comment]
Thanks, I'll give it a try.

**Comment by GMishx** [comment]
Hello @jb68 , did it solve your issue?

**Comment by janwels89** [comment]
I am Running into the same problem on Version: [3.10.0.9]
```
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "diff: missing operand after '/srv/fossology/repository/localhost/files/11/c6/45/11c64571a7d09ea0b470827f35081044a3025bbf.901f9bb997b92bd5a7410465d762c399.6055'"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "diff: Try 'diff --help' for more information."
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "0"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "PHP Warning:  pg_execute(): Query failed: ERROR:  insert or update on table "clearing_decision" violates foreign key constraint "clearing_decision_pfile_fk_fkey""
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "DETAIL:  Key (pfile_fk)=(0) is not present in table "pfile". in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 70"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "[2021-01-25 10:46:16] default.CRITICAL: ERROR:  insert or update on table "clearing_decision" violates foreign key constraint "clearing_decision_pfile_fk_fkey" DETAIL:  Key (pfile_fk)=(0) is not present in table "pfile". [] []"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "Caught exception while processing uploadId=10: error executing: Fossology\Lib\Dao\ClearingDao::createDecisionFromEvents: "
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "INSERT INTO clearing_decision ("
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  uploadtree_fk,"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  pfile_fk,"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  user_fk,"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  group_fk,"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  decision_type,"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  scope"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: ") VALUES ("
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  $1,"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  (SELECT pfile_fk FROM uploadtree WHERE uploadtree_pk=$1),"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  $2,"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  $3,"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  $4,"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "  $5) RETURNING clearing_decision_pk"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "   -- -- Array"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "("
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "    [0] => 1900225"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "    [1] => 3"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "    [2] => 3"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "    [3] => 5"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "    [4] => 0"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: ")"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "ERROR:  insert or update on table "clearing_decision" violates foreign key constraint "clearing_decision_pfile_fk_fkey""
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "DETAIL:  Key (pfile_fk)=(0) is not present in table "pfile".#0 /usr/local/share/fossology/lib/php/Db/ModernDbManager.php(68): Fossology\Lib\Db\DbManager->checkResult(false, 'Fossology\\Lib\\D...')"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#1 /usr/local/share/fossology/lib/php/Dao/ClearingDao.php(380): Fossology\Lib\Db\ModernDbManager->execute('Fossology\\Lib\\D...', Array)"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#2 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(396): Fossology\Lib\Dao\ClearingDao->createDecisionFromEvents('1900225', '3', '3', 5, 0, Array)"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#3 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(341): Fossology\Reuser\ReuserAgent->createCopyOfClearingDecision('1900225', '3', '3', Object(Fossology\Lib\Data\ClearingDecision))"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#4 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(317): Fossology\Reuser\ReuserAgent->copyClearingDecisionIfDifferenceIsSmall('/srv/fossology/...', NULL, Object(Fossology\Lib\Data\ClearingDecision), '1900225')"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#5 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(122): Fossology\Reuser\ReuserAgent->processEnhancedUploadReuse(Object(Fossology\Lib\Data\Tree\ItemTreeBounds), Object(Fossology\Lib\Data\Tree\ItemTreeBounds), '3')"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#6 /usr/local/share/fossology/lib/php/Agent/Agent.php(338): Fossology\Reuser\ReuserAgent->processUploadId(10)"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#7 /usr/local/share/fossology/reuser/agent/reuser.php(59): Fossology\Lib\Agent\Agent->run_scheduler_event_loop()"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#8 /usr/local/lib/fossology/fo_wrapper(77): require('/usr/local/shar...')"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#9 {main}agent failed on uploadId=10#0  Fossology\Lib\Agent\Agent->bail() called at [/usr/local/share/fossology/lib/php/Agent/Agent.php:349]"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#1  Fossology\Lib\Agent\Agent->run_scheduler_event_loop() called at [/usr/local/share/fossology/reuser/agent/reuser.php:59]"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: "#2  require(/usr/local/share/fossology/reuser/agent/reuser.php) called at [/usr/local/lib/fossology/fo_wrapper:77]"
2021-01-25 10:46:16 reuser [0] :: JOB[417].reuser[166.localhost]: agent failed with error code 1
2021-01-25 10:46:17 reuser [0] :: JOB[417].reuser[166.localhost]: agent failed, code: 0
```


```
SELECT * FROM uploadtree INNER JOIN pfile on pfile_pk = pfile_fk WHERE uploadtree_pk = 1900225;
```
returns ```(0 rows)```

```
DELETE FROM clearing_decision WHERE uploadtree_fk = 1900225;
```
returns ```DELETE 0```
