### ISSUE TITLE
Browse page not getting loaded in IE, PHP fatal error for dateTimeZone 

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#1778]
### Description

Browse page is not getting loaded because of PHP fatal in internet explorer.

#### How to reproduce

* Login to fossology server from internet explorer.

### Versions

* Last master:

### Apache logs

```
PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone (undefined) in /usr/local/share/fossology/lib/php/common-ui.php:304\nStack trace:
#0 /usr/local/share/fossology/lib/php/common-ui.php(304): DateTimeZone->__construct('undefined')
#1 /usr/local/share/fossology/www/ui/async/AjaxBrowse.php(199): Convert2BrowserTime('2020-07-10 13:0...')
#2 /usr/local/share/fossology/www/ui/async/AjaxBrowse.php(141): Fossology\\UI\\Ajax\\AjaxBrowse->showRow(Array, Object(Symfony\\Component\\HttpFoundation\\Request), '/repo/?mod=lice...', Array, Array, Array, Array, 1)
#3 /usr/local/share/fossology/www/ui/async/AjaxBrowse.php(106): Fossology\\UI\\Ajax\\AjaxBrowse->respondFolderGetTableData(Object(Symfony\\Component\\HttpFoundation\\Request))
#4 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(239): Fossology\\UI\\Ajax\\AjaxBrowse->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#5 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(271): Fossology\\Lib\\Plugin\\DefaultPlugin->getResponse()
#6 /usr/lo in /usr/local/share/fossology/lib/php/common-ui.php on line 304, referer: http://localhost:2211/repo/?mod=browse
```

**Comment by DineshDevarajan** [comment]
Hi @shaheemazmalmmd  i tried to use the fossology/fossology:latest image and tested this issue and browse page is working fine . Please let me know how are you testing this. is it the something like  [Install from source](https://github.com/fossology/fossology/wiki/Install-from-Source) ?
