### ISSUE TITLE
Fatal error during license_ref db init: tables can have at most 1600 columns

### ISSUE THREAD

**Issue by wla80** [fossology/fossology#1809]
Our team reported similar error in https://github.com/fossology/fossology/issues/1701 before. We hosted the fossology server and the db in a remote server and each time a fossology scan is required, we run a local fossology container (from our workspace) that connects to the fossology db in the remote server.

`fossology/lib/php/Db/Driver/Postgres.php on line 79
[2020-09-30 19:24:08] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  tables can have at most 1600 columns [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "license_ref" ADD COLUMN "rf_add_date" date DEFAULT now()
ERROR:  tables can have at most 1600 columns in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "li...')`

we tried to skip the license_ref init step by excluding **--licenseref** from `/usr/local/lib/fossology/fo-postinstall --common --database --licenseref` but it didn't work

**Comment by GMishx** [comment]
Hello @wla80, can you please let us more about:
1. Which version of PostgreSQL you are running?
1. Sharing the output of following query:
```sql
SELECT
  table_name AS table, ordinal_position AS ordinal, column_name,
  udt_name AS type, character_maximum_length AS modifier,
  CASE is_nullable WHEN 'YES' THEN false WHEN 'NO' THEN true END AS notnull,
  column_default AS default,
  col_description(table_name::regclass, ordinal_position) AS description
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'license_ref'
ORDER BY table_name, ordinal_position;
```

**Comment by wla80** [comment]
Hi @GMishx , thanks for following up. 
1. `postgres (PostgreSQL) 10.14 (Debian 10.14-1.pgdg90+1)`
2. 
[output.pdf](https://github.com/fossology/fossology/files/5337273/output.pdf)

**Comment by GMishx** [comment]
Thanks for providing the output. After matching the output you have shared with what I have with me, I noticed two things:

Output from my machine:
![image](https://user-images.githubusercontent.com/18077542/95287758-62ba1680-0884-11eb-8b01-a1ce2333604a.png)

Output shared:
![Screenshot_20201007_100549](https://user-images.githubusercontent.com/18077542/95288215-67cb9580-0885-11eb-9b36-47a30225f057.png)

1. The description of `rf_copyleft`, `rf_OSIapproved`, `rf_FSFfree`, `rf_GPLv2compatible`, and `rf_GPLv3compatible` are missing.
    - Is it intentional?
    - This causes the query to not match the schema of `fo-postinstall` and causes removal and alternation of the columns (the ordinal number is more than 200 for only those columns).
1. The default value for `rf_add_date` is missing which should be `now()`.

Can you please confirm there was no alternation done to the database and the `src/www/ui/core-schema.dat`?

**Comment by wla80** [comment]
Hi @GMishx ,

I don't think we intentionally (or need to) modify such data in the db and I also confirm we didn't modify `src/www/ui/core-schema.dat`. Commit messages of this file

```
commit 66a009d838fced4cd73ad9aecc4f07ee2b56bc54
Author: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
Date:   Wed Dec 11 11:58:08 2019 +0530

    feat(conf): add obligations to consider a particular license for its obligation to be listed in report
    
    Signed-off-by: Shaheem Azmal M MD <shaheem.azmal@siemens.com>

commit af3f5738db262a6b2a088a78eef3424301c63c1d
Author: Gaurav Mishra <mishra.gaurav@siemens.com>
Date:   Tue May 14 10:02:42 2019 +0530

    feat(license): Provide predefined license comments
    
    Provide a drop-down to user to pick a license comment from a predefined
    set of standard license comments.
    
    Signed-off-by: Gaurav Mishra <mishra.gaurav@siemens.com>

commit 9a3f86d646538f2ef9a1bf2e0caabd5149708c9f
Author: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
Date:   Fri Sep 20 16:33:31 2019 +0530

    fix(groups): add validations and remove CONSTRAINTS
```

Nevertheless, how can we recover it in this case

**Comment by wla80** [comment]
Hi @GMishx , I looked into fossology src code and for https://github.com/fossology/fossology/pull/1705, should licenseRef.json also be updated accordingly?

**Comment by GMishx** [comment]
Hello, as per the logs shared, the issue is with schema mismatch which is stored in `src/www/ui/core-schema.dat`. The `licenseRef.json` just stores the license relate information (data). So it should not be issue with that.

However, I tried with PostgreSQL 10.4, 11, 12 and 13 but couldn't replicate the issue. I am not sure what am I missing here. Also the issue #1818 reported by you is because of same thing.

**Comment by wla80** [comment]
Hi @GMishx , for our fossology scan architecture, the fossology webserver & psql database are hosted in the same machine (point A) on a Azure cloud server, and each time we need to scan something, there might be 3 - 4 simultaneously scans happening in a separate machine (point B e.g.) and each scan is launched in separate local docker containers within the same machine created from `docker run -p <port> fossology/fossology -e FOSSOLOGY_DB_HOST=<ip to the remote psql database>`. Do you see if the broken schema is possible related to such system design? thanks

**Comment by lmarie23** [comment]
Hi,
I think I found the root cause of this. When launching fossology from a container, the VERSION file is not present, but is used to determine the latest Release of database migration. That's what I understand from commit : https://github.com/fossology/fossology/commit/e08eeb71f012c4f661aa15f63088e03ba332b162#diff-652dd03bfdc338852b5f8a14cb7f323ec4b482813c05ed2b1445baa05d7420f1L399

In my local image I reverted this change and it works perfectly now.

I'm not sure the revert is the good option, but I need explanation on what is expected to be read from the VERSION file.

**Comment by janwels89** [comment]
I am still facing this issue with fossology containers from dockerhub deployed in my kubernetes environment:

```
*** Running postinstall for common actions***
*** Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
*** Making sure needed dirs exist with right ownership/permissions ***
*** clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.
      We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.
      Admin > Dashboard will show you the last time vacuum and analyze have been run.
NOTE: using external DB on host fossology-db
*** update the database and license_ref table ***
Old release was 4.5.1
PHP Warning:  pg_query(): Query failed: ERROR:  tables can have at most 1600 columns in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 68
[2025-03-26T14:18:07.790292+00:00] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  tables can have at most 1600 columns [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "license_candidate" ADD COLUMN "rf_user_fk_created" int4 DEFAULT 3
ERROR:  tables can have at most 1600 columns in /usr/local/share/fossology/lib/php/Db/DbManager.php:133
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(192): Fossology\Lib\Db\DbManager->checkResult()
#1 /usr/local/share/fossology/lib/php/libschema.php(320): Fossology\Lib\Db\DbManager->queryOnce()
#2 /usr/local/share/fossology/lib/php/libschema.php(173): fo_libschema->applyTables()
#3 /usr/local/lib/fossology/fossinit.php(189): fo_libschema->applySchema()
#4 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 133
```
