### ISSUE TITLE
Display error while changing upload permission

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1929]
### Description

If the scheduler is not working while adding new group permissions to an upload with reuse, a blank page is presented instead of showing error message.

#### How to reproduce

1. Upload a package and do some clearing.
2. Change the upload status to "Closed".
3. Create a new group.
4. Kill the scheduler daemon.
5. Goto Admin >> Upload Permissions and find the upload.
6. Add the newly created group with **<something> with reuse** as permission.
7. A blank page is loaded.

#### Screenshots

![image](https://user-images.githubusercontent.com/18077542/112466496-f8425780-8d8b-11eb-8a52-bac9a3d3d407.png)

### Versions

* Last commit id on master: aaec8d420e0d58f4e7663a9694e1fae44b42def6

#### Apache logs

```
PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /usr/local/share/fossology/www/ui/admin-scheduler.php on line 69, referer: http://localhost/repo/
PHP Stack trace:, referer: http://localhost/repo/
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/repo/
PHP   2. admin_scheduler->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/repo/
PHP   3. admin_scheduler->getResponse() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:467, referer: http://localhost/repo/
PHP   4. admin_scheduler->Output() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:383, referer: http://localhost/repo/
PHP   5. admin_scheduler->JobListOption('status') /usr/local/share/fossology/www/ui/admin-scheduler.php:270, referer: http://localhost/repo/
PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /usr/local/share/fossology/www/ui/admin-scheduler.php on line 69, referer: http://localhost/repo/?mod=admin_scheduler
PHP Stack trace:, referer: http://localhost/repo/?mod=admin_scheduler
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/repo/?mod=admin_scheduler
PHP   2. admin_scheduler->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/repo/?mod=admin_scheduler
PHP   3. admin_scheduler->getResponse() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:467, referer: http://localhost/repo/?mod=admin_scheduler
PHP   4. admin_scheduler->Output() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:383, referer: http://localhost/repo/?mod=admin_scheduler
PHP   5. admin_scheduler->JobListOption('status') /usr/local/share/fossology/www/ui/admin-scheduler.php:270, referer: http://localhost/repo/?mod=admin_scheduler
PHP Fatal error:  Uncaught Exception: Connection to the scheduler failed.  Is the scheduler running?<br>socket_connect() failed.\nReason: () Connection refused<br>\n\n in /usr/local/share/fossology/www/ui/page/UploadPermissionPage.php:177
Stack trace:
#0 /usr/local/share/fossology/www/ui/page/UploadPermissionPage.php(92): UploadPermissionPage->insertPermission()
#1 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(239): UploadPermissionPage->handle()
#2 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(271): Fossology\\Lib\\Plugin\\DefaultPlugin->getResponse()
#3 /usr/local/share/fossology/www/ui/index.php(64): Fossology\\Lib\\Plugin\\DefaultPlugin->execute()
#4 {main}\n  thrown in /usr/local/share/fossology/www/ui/page/UploadPermissionPage.php on line 177, referer: http://localhost/repo/?mod=upload_permissions&folder=5&upload=150&alluploadsperm=0&newperm=0&newgroup=6
```

Suggestion: Use the `message` parameter for Twig: https://github.com/fossology/fossology/blob/aaec8d420e0d58f4e7663a9694e1fae44b42def6/src/lib/php/UI/template/include/base.html.twig#L39

**Comment by itssingh** [comment]
@GMishx I would like to work on this issue:)

**Comment by GMishx** [comment]
Sure, assigning it to you.

**Comment by Aditi-Roy-coder** [comment]
I would like to work on this issue.

**Comment by Rahulrajak1710** [comment]
@GMishx I would like to work on this issue

**Comment by GMishx** [comment]
Please go ahead with it @Rahulrajak1710
