### ISSUE TITLE
After adding a license comment, the 'Processing' textbox shows forever

### ISSUE THREAD

**Issue by drej** [fossology/fossology#2014]
### Description

FOSSology 3.8.1 ON RHEL 7&8
After adding some license comment text, the page shows me a textbox with 'Processing' then the page won't change anymore.
I can still make some changes, like add an user decision license, and I check the db found the change has been recorded into the db.
I can leave that page using FOSSology as usual but that 'Processing' box would never disappear.

If I delete comments in clearing_event from db, everything backs to normal.

#### How to reproduce

I am not sure what is the trigger exactly, but I found that add some double bytes character (like Japanese) and new line would be very easy to reproduce this bug

Maybe you can try the text below ( 2 lines as a whole):

日本語
改行

#### Screenshots

![image](https://user-images.githubusercontent.com/1217733/122005197-4cd7fa80-cdf0-11eb-893e-53f2e8bffa2c.png)

### Versions

* FOSSology 3.8.1
* both RHEL 7 and 8

**Comment by GMishx** [comment]
Please check the network tab in the developer tool for your browser and check if there is a 500 error when you perform this operation.

Please share the Apache error log so we can help you further. They will be available at `/var/log/apache2/error.log` on the `web` container. Or even check the `docker logs -f web` and please share the logs.

**Comment by drej** [comment]
@GMishx Thank you for responding.
There is a 500 error when loading jquery.min.js
![image](https://user-images.githubusercontent.com/1217733/123900983-116b2d80-d9a5-11eb-9d29-227d326f7658.png)
and I checked the error.log:
```bash
PHP Fatal error:  Uncaught InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in /usr/local/share/fossology/vendor/symfony/http-foundation/JsonResponse.php:168\nStack trace:\n#0 /usr/local/share/fossology/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\\Component\\HttpFoundation\\JsonResponse->setData(false)\n#1 /usr/local/share/fossology/www/ui/ajax-clearing-view.php(208): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array)\n#2 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(381): AjaxClearingView->Output()\n#3 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(465): FO_Plugin->getResponse()\n#4 /usr/local/share/fossology/www/ui/index.php(64): FO_Plugin->execute()\n#5 {main}\n  thrown in /usr/local/share/fossology/vendor/symfony/http-foundation/JsonResponse.php on line 168, referer: http://fossology-addr/repo/?mod=view-license&upload=27&item=151
```

**Comment by GMishx** [comment]
Oh, looks like issue with some non-UTF8 characters in license text. It should've been fixed by #1994 and #1996

**Comment by drej** [comment]
@GMishx Thank you for answering
I tested the latest version on Docker hub (ver 3.10.0.83), the keep showing 'Processing...' has gone, but I found another thing:
![image](https://user-images.githubusercontent.com/1217733/123909634-4763de00-d9b4-11eb-8a1d-85a47581bd7b.png)
The license text in background has broken, which is showing fine in the popup textbox.

**Comment by GMishx** [comment]
:grimacing:

Can you please provide the text phrase for testing?

**Comment by drej** [comment]
@GMishx It is also in the first comment:
```text
日本語
改行
```
By the way it means "Japanese" and "change a line" :)

**Comment by drej** [comment]
@GMishx I think a little change could fix this problem:
file: src/www/ui/ajax-clearing-view.php
function getBuildClearingsForSingleFile()
![image](https://user-images.githubusercontent.com/1217733/124068504-9c1b5d80-da75-11eb-842b-fceb2928a6c2.png)
