### ISSUE TITLE
Reuser fails  after upgrading to 4.0 version

### ISSUE THREAD

**Issue by lakshmibhavani1** [fossology/fossology#2200]
### Description

We are unable to reuse older uploads after upgrading fossology to 4.0.0. The file which was uploaded in Sept, 2020 when reused now, fails in the 4.0 version. There was no issue prior to the 4.0 release. We are unable to figure out the exact reason why the reuser is failing. Please check the logs which we found on the **show jobs** page for the reuse agent.

#### ERROR LOGS FOR REUSE AGENT - My recent jobs

```
"Caught exception while processing uploadId=50490: Existing Statement mismatch: Fossology\Lib\Dao\ClearingDao::getFileClearingsFolder.(ut.lft BETWEEN $1 AND $2).uploadtree_a.current#0 /usr/local/share/fossology/lib/php/Dao/ClearingDao.php(244): Fossology\Lib\Db\ModernDbManager->prepare('Fossology\\Lib\\D...', 'WITH decision A...')"
"#1 /usr/local/share/fossology/lib/php/Dao/ClearingDao.php(208): Fossology\Lib\Dao\ClearingDao->getDecisionsFromCte('WITH decision A...', 'Fossology\\Lib\\D...', Array)"
"#2 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(261): Fossology\Lib\Dao\ClearingDao->getFileClearingsFolder(Object(Fossology\Lib\Data\Tree\ItemTreeBounds), '148')"
"#3 /usr/local/share/fossology/reuser/agent/ReuserAgent.php(124): Fossology\Reuser\ReuserAgent->processUploadReuse(Object(Fossology\Lib\Data\Tree\ItemTreeBounds), Object(Fossology\Lib\Data\Tree\ItemTreeBounds), '148')"
"#4 /usr/local/share/fossology/lib/php/Agent/Agent.php(338): Fossology\Reuser\ReuserAgent->processUploadId(50490)"
"#5 /usr/local/share/fossology/reuser/agent/reuser.php(59): Fossology\Lib\Agent\Agent->run_scheduler_event_loop()"
"#6 /usr/local/lib/fossology/fo_wrapper(77): require('/usr/local/shar...')"
"#7 {main}agent failed on uploadId=50490#0  Fossology\Lib\Agent\Agent->bail() called at [/usr/local/share/fossology/lib/php/Agent/Agent.php:349]"
"#1  Fossology\Lib\Agent\Agent->run_scheduler_event_loop() called at [/usr/local/share/fossology/reuser/agent/reuser.php:59]"
"#2  require(/usr/local/share/fossology/reuser/agent/reuser.php) called at [/usr/local/lib/fossology/fo_wrapper:77]"
agent failed with error code 1
agent failed, code: 0
```

### Observation from our end:

1. We tried to test reuse if it is working for new uploads. Result: working
2. We tried checking the pfile and also checked whether it's present in the repository path. Result: present

Note: Reuser works well for newer uploads.

**Comment by GMishx** [comment]
I think the issue was fixed by https://github.com/fossology/fossology/pull/2164

Can you please confirm if possible @lakshmibhavani1 ?

**Comment by lakshmibhavani1** [comment]
issue fixed after adding the code changes suggested by community
