### ISSUE TITLE
DB migration error

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#2296]
### Description

When migrating from 3.10 to 4.0, an issue whenever is so happens that there is no user with id 3 in the database.

During DB migration:
1. a new column is added in the table `license_candidate`, referring to a user primary key. The default value is set to 3: https://github.com/fossology/fossology/blob/43924f05229e03bfa1c86eb285127f9f0b93d409/src/www/ui/core-schema.dat#L1153
2. then a constraint enforces that the referenced users do exist: https://github.com/fossology/fossology/blob/43924f05229e03bfa1c86eb285127f9f0b93d409/src/www/ui/core-schema.dat#L2389

The problem arises if no user user id 3 exists in the database, the constraint cannot be added since it cannot be satisfied:
```
Old release was 3.3.0
PHP Warning:  pg_query(): Query failed: ERROR:  insert or update on table "license_candidate" violates foreign key constraint "license_candidate_rf_user_fk_created_fkey"
DETAIL:  Key (rf_user_fk_created)=(3) is not present in table "users". in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
[2022-08-17 12:17:53] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  insert or update on table "license_candidate" violates foreign key constraint "license_candidate_rf_user_fk_created_fkey"
DETAIL:  Key (rf_user_fk_created)=(3) is not present in table "users". [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "license_candidate" ADD CONSTRAINT "license_candidate_rf_user_fk_created_fkey" FOREIGN KEY ("rf_user_fk_created") REFERENCES "users" ("user_pk") ON UPDATE SET NULL ON DELETE SET NULL;

ERROR:  insert or update on table "license_candidate" violates foreign key constraint "license_candidate_rf_user_fk_created_fkey"
DETAIL:  Key (rf_user_fk_created)=(3) is not present in table "users". in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "li...')
#1 /usr/local/share/fossology/lib/php/libschema.php(95): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "li...', 'fo_libschema::a...')
#2 /usr/local/share/fossology/lib/php/libschema.php(472): fo_libschema->applyOrEchoOnce('ALTER TABLE "li...', 'fo_libschema::a...')
#3 /usr/local/share/fossology/lib/php/libschema.php(192): fo_libschema->applyConstraints()
#4 /usr/loc in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144
```

#### How to reproduce

1. Start with fossology versino 3.10
2. add at least a custom licence
3. delete user with id 3
4. migrate to version 4.0

### Versions
At maximum, between 3.10 and 4.0

**Comment by NicolasToussaint** [comment]
And by the way, the workaround I applied ;

I had to manually create the new columns (with user 3, before I knew that was the problem), so you can create the new columns with a correct default value from the start:

```
ALTER TABLE license_candidate ADD COLUMN rf_user_fk_created int4 DEFAULT 3;
ALTER TABLE license_candidate ALTER COLUMN rf_user_fk_created DROP NOT NULL;
COMMENT ON COLUMN license_candidate.rf_user_fk_created IS 'user who created';

ALTER TABLE license_candidate ADD COLUMN rf_user_fk_modified int4;
ALTER TABLE license_candidate ALTER COLUMN rf_user_fk_modified DROP NOT NULL;
COMMENT ON COLUMN license_candidate.rf_user_fk_modified IS 'user who modified';

```
If too late, all you have to do if update the rows to change the column `rf_user_fk_created`

**Comment by NicolasToussaint** [comment]
no need to ever fix this, closing issue
