### ISSUE TITLE
scheduler keeping restarting but health check looks just fine

### ISSUE THREAD

**Issue by wang-fut** [fossology/fossology#2558]
### Description

I create a fossology instance from blank using docker image tag 4.3.0
After containers started, I can access fossology from web brower but
docker compose ps shows output below:
![image](https://github.com/fossology/fossology/assets/95271446/a41c97fe-38a2-4405-99f9-aaae6c5eed2d)
but api check shows scheduler works fine
![image](https://github.com/fossology/fossology/assets/95271446/bc7ba562-55ca-4ebf-89df-b0e52b8f73d0)
I checked scheduler status from web page, not that fine
![image](https://github.com/fossology/fossology/assets/95271446/0e53db5a-50cb-414b-8d1d-a7fd923c0c46)

#### How to reproduce

I don't think i did anything special so i just paste my compose.yml here:

version: '3.5'
services:
  scheduler:
    image: fossology/fossology:4.3.0
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
    command: scheduler
    depends_on:
      - db
    volumes:
      - repository:/srv/fossology/repository/
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 5s
      timeout: 5s
      retries: 2
      # start-period: 30s
  web:
    image: fossology/fossology:4.3.0
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
      - FOSSOLOGY_SCHEDULER_HOST=scheduler
    command: web
    ports:
      - "8081:80"
    depends_on:
      - db
      - scheduler
    volumes:
      - repository:/srv/fossology/repository/
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf localhost/repo/api/v1/health | grep -q '{\"status\":\"OK\",' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_DB=fossology
      - POSTGRES_USER=fossy
      - POSTGRES_PASSWORD=fossy
      - POSTGRES_INITDB_ARGS='-E SQL_ASCII'
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start-period: 10s

volumes:
  database:
  repository:

### Versions

* 4.3.0
by the way this image doesnot show correct version number on the web page
![image](https://github.com/fossology/fossology/assets/95271446/dfa58998-87b3-485e-9602-d947350ff6b1)

### Logs

fossology-scheduler-1  | NOTE: Repository already exists at /srv/fossology/repository
fossology-scheduler-1  | NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.
fossology-scheduler-1  |       We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.
fossology-scheduler-1  |       Admin > Dashboard will show you the last time vacuum and analyze have been run.
fossology-scheduler-1  | NOTE: using external DB on host db
fossology-scheduler-1  | *** update the database and license_ref table ***
fossology-scheduler-1  | Old release was
fossology-scheduler-1  | PHP Warning:  pg_query(): Query failed: ERROR:  tables can have at most 1600 columns in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 68
fossology-scheduler-1  | [2023-08-02T04:31:31.300916+00:00] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  tables can have at most 1600 columns [] []
fossology-scheduler-1  | PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "license_candidate" ADD COLUMN "group_fk" int8
fossology-scheduler-1  |
fossology-scheduler-1  | ERROR:  tables can have at most 1600 columns in /usr/local/share/fossology/lib/php/Db/DbManager.php:133
fossology-scheduler-1  | Stack trace:
fossology-scheduler-1  | #0 /usr/local/share/fossology/lib/php/Db/DbManager.php(192): Fossology\Lib\Db\DbManager->checkResult()
fossology-scheduler-1  | #1 /usr/local/share/fossology/lib/php/libschema.php(320): Fossology\Lib\Db\DbManager->queryOnce()
fossology-scheduler-1  | #2 /usr/local/share/fossology/lib/php/libschema.php(173): fo_libschema->applyTables()
fossology-scheduler-1  | #3 /usr/local/lib/fossology/fossinit.php(189): fo_libschema->applySchema()
fossology-scheduler-1  | #4 {main}
fossology-scheduler-1  |   thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 133

I checked "license_candidate" table, regular columes only

fossology=# select * from license_candidate;
 rf_pk | rf_shortname | rf_text | rf_url | rf_add_date | rf_copyleft | rf_OSIapproved | rf_fullname | rf_FSFfree | rf_GPLv2compatible | rf_GPLv3compa
tible | rf_notes | rf_Fedora | marydone | rf_active | rf_text_updatable | rf_md5 | rf_detector_type | rf_source | rf_risk | rf_flag | rf_spdx_id | gr
oup_fk | rf_creationdate | rf_lastmodified | rf_user_fk_created | rf_user_fk_modified
-------+--------------+---------+--------+-------------+-------------+----------------+-------------+------------+--------------------+--------------
------+----------+-----------+----------+-----------+-------------------+--------+------------------+-----------+---------+---------+------------+---
-------+-----------------+-----------------+--------------------+---------------------
(0 rows)

**Comment by GMishx** [comment]
So, the web and scheduler containers are almost the same. In web container, the scheduler daemon is not started, only in scheduler container.

So, `curl localhost:8081/repo/api/v1/health` will give you the scheduler daemon status from web container.

One fix will be to remove the health check on this endpoint from the web container.

**Comment by GMishx** [comment]
We tried to fix the issue with #1701. However, it seems like there is not enough time in between the restarts and the `fo-postinstall` script couldn't finish in time and called again due to the restart. This would lead to the `1600 column` issue.

**Comment by kannan-seenivasan** [comment]
Hi @wang-fut  / @GMishx , 

Could you kindly let me know if we have a solution for this? We're encountering the same issue in FOSSology version 4.4.0 with postgres 16.2.

```
PHP Warning:  pg_query(): Query failed: ERROR:  tables can have at most 1600 columns in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 68

/usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  tables can have at most 1600 columns
 
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "license_candidate" ADD COLUMN "group_fk" int8
 
ERROR:  tables can have at most 1600 columns in /usr/local/share/fossology/lib/php/Db/DbManager.php:133
 
```
