### ISSUE TITLE
scancode failed

### ISSUE THREAD

**Issue by g-sahil22** [fossology/fossology#2667]
### Description

scancode agent failed

### Versions

Version: [4.4.0.4], Branch: [master], Commit: [#19fad1] 2024/01/10 14:51 +00:00 built @ 2024/01/10 14:54 +00:00

#### Job logs

2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "Traceback (most recent call last):"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "  File "/usr/local/share/fossology/scancode/agent/runscanonfiles.py", line 11, in "
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "    from scancode import api"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "  File "/home/fossy/pythondeps/scancode/__init__.py", line 16, in "
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "    from commoncode import fileutils"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "  File "/home/fossy/pythondeps/commoncode/fileutils.py", line 21, in "
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "    from scancode_config import scancode_temp_dir as _base_temp_dir"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "  File "/home/fossy/pythondeps/scancode_config.py", line 148, in "
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "    _create_dir(scancode_cache_dir)"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "  File "/home/fossy/pythondeps/scancode_config.py", line 52, in _create_dir"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "    os.makedirs(location)"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "  File "/usr/lib/python3.9/os.py", line 215, in makedirs"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "    makedirs(head, exist_ok=exist_ok)"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "  File "/usr/lib/python3.9/os.py", line 215, in makedirs"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "    makedirs(head, exist_ok=exist_ok)"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "  File "/usr/lib/python3.9/os.py", line 225, in makedirs"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "    mkdir(name, mode)"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "PermissionError: [Errno 13] Permission denied: '/root/.cache'"
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: "FATAL ../src/scancode/agent/scancode_wrapper.cc.80: could not execute scancode command: PYTHONPATH='/home/fossy/pythondeps/' python3 runscanonfiles.py -lceu -m 50 /tmp/filewfBaAa /tmp/file31OWpa "
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: agent failed with error code 1
2024-01-11 22:36:04 scancode [0] :: JOB[63].scancode[9548.localhost]: agent failed, code: 1

**Comment by GMishx** [comment]
Hey @g-sahil22 , can you please share how the FOSSology was installed? I see in the logs it says scancode failed to create the dir `/root/.cache` which should ideally be `$HOME/.cache`. Which means the scancode was started by root user instead of `fossy` user.

**Comment by g-sahil22** [comment]
I build the https://github.com/juice-shop/juice-shop/ code and then zip it and upload it

**Comment by submachine** [comment]
I get an identical error when trying to run fossology on a recent glibc tarball. My installation method was to use `podman pull fossology/fossology` on my Fedora 39 box, and using from within the container, i.e. `docker run -p 8081:80 fossology/fossology`.

**Comment by dineshr93** [comment]
@GMishx  I am getting the same error when i tried to install in stable release 

version: **Version: [4.4.0], Branch: [HEAD], Commit: [#903df0] 2024/01/15 09:27 +00:00 built @ 2024/02/15 09:21 +00:00**

this fixed issue in the token  https://github.com/fossology/fossology/issues/2682


```
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "Traceback (most recent call last):"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "  File "/usr/local/share/fossology/scancode/agent/runscanonfiles.py", line 11, in "
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "    from scancode import api"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "  File "/home/fossy/pythondeps/scancode/__init__.py", line 16, in "
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "    from commoncode import fileutils"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "  File "/home/fossy/pythondeps/commoncode/fileutils.py", line 21, in "
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "    from scancode_config import scancode_temp_dir as _base_temp_dir"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "  File "/home/fossy/pythondeps/scancode_config.py", line 148, in "
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "    _create_dir(scancode_cache_dir)"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "  File "/home/fossy/pythondeps/scancode_config.py", line 52, in _create_dir"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "    os.makedirs(location)"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "  File "/usr/lib/python3.9/os.py", line 215, in makedirs"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "    makedirs(head, exist_ok=exist_ok)"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "  File "/usr/lib/python3.9/os.py", line 215, in makedirs"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "    makedirs(head, exist_ok=exist_ok)"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "  File "/usr/lib/python3.9/os.py", line 225, in makedirs"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "    mkdir(name, mode)"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "PermissionError: [Errno 13] Permission denied: '/root/.cache'"
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: "FATAL ../src/scancode/agent/scancode_wrapper.cc.80: could not execute scancode command: PYTHONPATH='/home/fossy/pythondeps/' python3 runscanonfiles.py -lceu -m 50 /tmp/filewAwMvv /tmp/file1pUHhu "
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: agent failed with error code 1
2024-02-15 09:29:23 scancode [0] :: JOB[2206].scancode[718.localhost]: agent failed, code: 1
```

Initially I had no execute permission so I change the file permission and rebuild redploy the via docker-compose and above problem persists.
```
/usr/local/src/fossology$ ll src/scancode/agent/runscanonfiles.py
-rwxr-xr-x 1 dinesh users 6667 Feb 15 09:15 src/scancode/agent/runscanonfiles.py*
```

**Comment by kannan-seenivasan** [comment]
Hi @g-sahil22 / @dineshr93,

Setting the following environment variable ```SCANCODE_CACHE='/home/fossy/.cache``` on the container level, fixed the scan code issue for us. 

or enforce in the below. 
https://github.com/fossology/fossology/blob/4.4.0/src/scancode/agent/scancode_wrapper.cc#L73

**Comment by dvjsharma** [comment]
Fixed in #2692. PTAL
