### ISSUE TITLE
Database migration fails from 4.3.0 to 4.4.0

### ISSUE THREAD

**Issue by eschenbachertq** [fossology/fossology#2679]
### Description

Database migration fails during update from 4.3.0 to 4.4.0.

#### How to reproduce

`sudo /usr/local/lib/fossology/fo-postinstall`

### Versions

* FOSSology: tagged versions: 4.3.0 -> 4.4.0

* Operating System (lsb_release -a):
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

### Logs

```
$ sudo /usr/local/lib/fossology/fo-postinstall
*** Running postinstall for everything ***
*** Running postinstall for common actions***
*** Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
*** Making sure needed dirs exist with right ownership/permissions ***
*** clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.
      We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.
      Admin > Dashboard will show you the last time vacuum and analyze have been run.
*** Running postinstall for web-only actions***
*** Setting up the FOSSology database ***
NOTE: fossology database already exists, not creating
*** Checking for plpgsql support ***
NOTE: plpgsql already exists in fossology database, good
*** Checking for 'uuid-ossp' support ***
NOTE: 'uuid-ossp' already exists in fossology database, good
*** update the database and license_ref table ***
Old release was 4.3.0
PHP Warning:  pg_query(): Query failed: ERROR:  cannot drop column agent_rev_old of table agent because other objects depend on it
DETAIL:  view runstat_up_agent depends on column agent_rev_old of table agent
HINT:  Use DROP ... CASCADE to drop the dependent objects too. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 68
[2024-02-07T13:43:46.656719+01:00] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  cannot drop column agent_rev_old of table agent because other objects depend on it DETAIL:  view runstat_up_agent depends on column agent_rev_old of table agent HINT:  Use DROP ... CASCADE to drop the dependent objects too. [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "agent" DROP COLUMN "agent_rev_old"

ERROR:  cannot drop column agent_rev_old of table agent because other objects depend on it
DETAIL:  view runstat_up_agent depends on column agent_rev_old of table agent
HINT:  Use DROP ... CASCADE to drop the dependent objects too. in /usr/local/share/fossology/lib/php/Db/DbManager.php:133
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(192): Fossology\Lib\Db\DbManager->checkResult()
#1 /usr/local/share/fossology/lib/php/libschema.php(83): Fossology\Lib\Db\DbManager->queryOnce()
#2 /usr/local/share/fossology/lib/php/libschema.php(323): fo_libschema->applyOrEchoOnce()
#3 /usr/local/share/fossology/lib/php/libschema.php(168): fo_libschema->applyTables()
#4 /usr/local/lib/fossology/fossinit.php(189): fo_libschema->applySchema()
#5 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 133
```

When I view table schema for `agent`, I don't see column `agent_rev_old`:

```
fossology=> \d agent
                                           Table "public.agent"
    Column     |           Type           | Collation | Nullable |                 Default
---------------+--------------------------+-----------+----------+-----------------------------------------
 agent_pk      | integer                  |           | not null | nextval('agent_agent_pk_seq'::regclass)
 agent_name    | character varying(32)    |           | not null |
 agent_rev     | character varying(32)    |           |          |
 agent_desc    | character varying(255)   |           |          |
 agent_enabled | boolean                  |           |          | true
 agent_parms   | text                     |           |          |
 agent_ts      | timestamp with time zone |           |          | now()
Indexes:
    "agent_pkey" PRIMARY KEY, btree (agent_pk)
    "agent_unique_name_rev" UNIQUE CONSTRAINT, btree (agent_name, agent_rev)
Referenced by:
    TABLE "scancode_author" CONSTRAINT "agent_fk" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "ipra" CONSTRAINT "agent_fk" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "scancode_copyright" CONSTRAINT "agent_fk" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "ars_master" CONSTRAINT "ars_agent_fk_fkey" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk)
    TABLE "author" CONSTRAINT "author_agent_fk_fkey" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "bucket_file" CONSTRAINT "bf_bucket_agent_fk" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk)
    TABLE "bucket_container" CONSTRAINT "bucket_container_agent_fk_fkey" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk)
    TABLE "bucket_container" CONSTRAINT "bucket_container_nomosagent_pk_fkey" FOREIGN KEY (nomosagent_fk) REFERENCES agent(agent_pk)
    TABLE "bucket_file" CONSTRAINT "bucket_file_nomosagent_pk_fkey" FOREIGN KEY (nomosagent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "clixml_ars" CONSTRAINT "clixml_ars_agent_fk_fkc" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk)
    TABLE "copyright" CONSTRAINT "copyright_agent_fk_fkey" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "copyright_spasht" CONSTRAINT "copyright_spasht_agent_fk_fkey" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "decisionexporter_ars" CONSTRAINT "decisionexporter_ars_agent_fk_fkc" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk)
    TABLE "decisionimporter_ars" CONSTRAINT "decisionimporter_ars_agent_fk_fkc" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk)
    TABLE "ecc" CONSTRAINT "ecc_agent_fk_fkey" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "ipra" CONSTRAINT "ipra_agent_fk_fkey" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "ipra_ars" CONSTRAINT "ipra_ars_agent_fk_fkc" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk)
    TABLE "keyword" CONSTRAINT "keyword_agent_fk_fkey" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk) ON DELETE CASCADE
    TABLE "scancode_ars" CONSTRAINT "scancode_ars_agent_fk_fkc" FOREIGN KEY (agent_fk) REFERENCES agent(agent_pk)
```

**Comment by csampaio26** [comment]
How do you run that migrate script on a database outside the machine?

**Comment by eschenbachertq** [comment]
What exactly do you mean by "outside the machine"?

**Comment by carstensh** [comment]
I have the same issue using the Docker container and an external postgres intance:
```
*** update the database and license_ref table ***
Old release was 4.3.0
PHP Warning:  pg_query(): Query failed: ERROR:  cannot drop column agent_rev_old of table agent because other objects depend on it
DETAIL:  view runstat_up_agent depends on column agent_rev_old of table agent
HINT:  Use DROP ... CASCADE to drop the dependent objects too. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 68
[2024-07-04T09:19:31.676896+00:00] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  cannot drop column agent_rev_old of table agent because other objects depend on it DETAIL:  view runstat_up_agent depends on column agent_rev_old of table agent HINT:  Use DROP ... CASCADE to drop the dependent objects too. [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "agent" DROP COLUMN "agent_rev_old"

ERROR:  cannot drop column agent_rev_old of table agent because other objects depend on it
DETAIL:  view runstat_up_agent depends on column agent_rev_old of table agent
HINT:  Use DROP ... CASCADE to drop the dependent objects too. in /usr/local/share/fossology/lib/php/Db/DbManager.php:133
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(192): Fossology\Lib\Db\DbManager->checkResult()
#1 /usr/local/share/fossology/lib/php/libschema.php(83): Fossology\Lib\Db\DbManager->queryOnce()
#2 /usr/local/share/fossology/lib/php/libschema.php(323): fo_libschema->applyOrEchoOnce()
#3 /usr/local/share/fossology/lib/php/libschema.php(168): fo_libschema->applyTables()
#4 /usr/local/lib/fossology/fossinit.php(189): fo_libschema->applySchema()
#5 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 133
```

**Comment by GMishx** [comment]
The column `agent_rev` had its datatype changed. Once there is a change, FOSSology copies the column adding `_old` suffix, delete the old column and remove the `_old` suffix. For a quick fix, you can do the manual change as follows:
```sql
ALTER TABLE "agent" ALTER COLUMN "agent_rev" TYPE text;
```

You can connect to the Database using `psql`

**Comment by carstensh** [comment]
Thanks for the information, that doesn't quite work as it is used in a view:
```
fossology=> ALTER TABLE "agent" ALTER COLUMN "agent_rev" TYPE text;
ERROR:  cannot alter type of a column used by a view or rule
DETAIL:  rule _RETURN on view runstat_up_agent depends on column "agent_rev"
```

**Comment by GMishx** [comment]
Oh, you are using FOSSology for long it seems :-)

The view `runstat_up_agent` is not used any more and can be dropped.

```sql
DROP VIEW runstat_up_agent CASCADE;
```

**Comment by carstensh** [comment]
:D 

That worked- thanks for your help!
