### ISSUE TITLE
Docker: Permission denied: '/root/.cache'"

### ISSUE THREAD

**Issue by xsuchy** [fossology/fossology#2691]
### Description

When using Fossology in a Docker I get error when scanner scans uploaded tarball

#### How to reproduce

1. docker run -p 8081:80 fossology/fossology
2. upload a tar ball - I used https://github.com/IBM/python-sdk-core/archive/refs/tags/v3.18.0.tar.gz but IMO any tarball will go.
3. Check the jobs.

the job of scancode agent fails with:

```
Log	

2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "Traceback (most recent call last):"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/usr/local/share/fossology/scancode/agent/runscanonfiles.py", line 11, in "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    from scancode import api"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/home/fossy/pythondeps/scancode/__init__.py", line 16, in "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    from commoncode import fileutils"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/home/fossy/pythondeps/commoncode/fileutils.py", line 21, in "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    from scancode_config import scancode_temp_dir as _base_temp_dir"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/home/fossy/pythondeps/scancode_config.py", line 148, in "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    _create_dir(scancode_cache_dir)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/home/fossy/pythondeps/scancode_config.py", line 52, in _create_dir"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    os.makedirs(location)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/usr/lib/python3.9/os.py", line 215, in makedirs"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    makedirs(head, exist_ok=exist_ok)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/usr/lib/python3.9/os.py", line 215, in makedirs"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    makedirs(head, exist_ok=exist_ok)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/usr/lib/python3.9/os.py", line 225, in makedirs"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    mkdir(name, mode)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "PermissionError: [Errno 13] Permission denied: '/root/.cache'"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "FATAL ../src/scancode/agent/scancode_wrapper.cc.80: could not execute scancode command: PYTHONPATH='/home/fossy/pythondeps/' python3 runscanonfiles.py -l -m 50 /tmp/fileCEMUHS /tmp/filepeK0BU "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: agent failed with error code 1
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: agent failed, code: 1
```
 
### Versions

Version: [4.4.0.7], Branch: [master], Commit: [#82757a] 2024/02/21 16:10 +00:00 built @ 2024/02/21 16:12 +00:00
Host is Fedora 39

**Comment by dvjsharma** [comment]
Hi @GMishx, 

I've looked into this issue. Currently we are using [scancode-wrapper.cc](https://github.com/fossology/fossology/blob/7ea0096a87ef6a4afee1063a4662b248e8fc7275/src/scancode/agent/scancode_wrapper.cc#L65-L88) file to construct the command to execute `runscanonfiles.py`. I checked the permissions of both scripts, and I noticed a change in the `user` and `group` for the `.cache` directory.

![Screenshot from 2024-03-05 02-45-18](https://github.com/fossology/fossology/assets/119073504/b33fbcb9-2f63-45a9-a648-c0fa0597878d)

![Screenshot from 2024-03-05 02-48-31](https://github.com/fossology/fossology/assets/119073504/45890590-7f1a-4b52-99a4-467e313be395)

This indicates that the `fossy` user is attempting to create a directory that needs `root` access. I'm unsure about the ideal solution for this. Any insights would be greatly appreciated. Please take a look. 

Thank you!

**Comment by kannan-seenivasan** [comment]
Hi @xsuchy  / @GMishx  / @dvjsharma ,

Setting the following environment variable ```SCANCODE_CACHE='/home/fossy/.cache``` fixed the scan code issue for us. 

or enforcing in the below. 
https://github.com/fossology/fossology/blob/4.4.0/src/scancode/agent/scancode_wrapper.cc#L73

**Comment by dvjsharma** [comment]
Thank you @kannan-seenivasan.
I discovered a similar solution during my research. The Scancode toolkit already contains a related issue that closely mirrors ours, where the calling users are not the same ([#2355](https://github.com/nexB/scancode-toolkit/issues/2355) & [#357](https://github.com/nexB/scancode-toolkit/issues/357)). To tackle this, they have introduced options and environment variables. Please see [CHANGELOG.rst](https://github.com/nexB/scancode-toolkit/blob/66d71661f5ede54cb0f3b36d7663c92a67030299/CHANGELOG.rst#L2009-L2011).

I tested the solution by adding the `SCANCODE_CACHE` environment variable at the container level in the `docker-compose.yml` file, and it worked perfectly. There was no need to modify `scancode_wrapper.cc` since the issue did not exist in the local installation (which was also tested). However, even if we were to update it, I believe using the `--cache-dir` option would be a more suitable approach.

I've submitted a PR to update the `docker-compose.yml`, which will resolve this issue and #2667. I will make the necessary modifications as advised.

CC @GMishx
