### ISSUE TITLE
Fossology postinstall fails after restarting container

### ISSUE THREAD

**Issue by miwurster** [fossology/fossology#2801]
### Description

We built a Helm chart deploying Fossology to our cluster. We connect to a external database running in Google Cloud. The `web` process and the `scheduler` process are running in different containers, but in the same Kubernetes pod.

When we first start the deployment, everything works find and the app is reachable. During the first start, the logs also show that the database has been successfully initialized. However, if we restart the Kubernetes Pod (eg. on a node switch or something similar), the `postinstall` fails with the error message below:

```
*** Running postinstall for common actions***
*** Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
*** Making sure needed dirs exist with right ownership/permissions ***
*** clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.
      We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.
      Admin > Dashboard will show you the last time vacuum and analyze have been run.
NOTE: using external DB on host staging-fossology-postgresql.planqk-testing.svc.cluster.local
*** update the database and license_ref table ***
Old release was 
PHP Warning:  pg_query(): Query failed: ERROR:  column "rf_spdx_id" of relation "license_ref" already exists in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 68
[2024-07-30T17:42:33.984601+00:00] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "rf_spdx_id" of relation "license_ref" already exists ] ]
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: ALTER TABLE "license_ref" ADD COLUMN "rf_spdx_id" text DEFAULT NULL

ERROR:  column "rf_spdx_id" of relation "license_ref" already exists in /usr/local/share/fossology/lib/php/Db/DbManager.php:133
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(192): Fossology\Lib\Db\DbManager->checkResult()
#1 /usr/local/share/fossology/lib/php/libschema.php(320): Fossology\Lib\Db\DbManager->queryOnce()
#2 /usr/local/share/fossology/lib/php/libschema.php(170): fo_libschema->applyTables()
#3 /usr/local/lib/fossology/fossinit.php(189): fo_libschema->applySchema()
#4 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 133
```

Do we miss something here? Any help is appreciated.

#### How to reproduce

- Deploy the helm chart to your cluster: [fossology.zip](https://github.com/user-attachments/files/16431679/fossology.zip)
- Wait till the first start completed
- Restart the fossology deployment 

### Versions

* currently we use Fossology 4.3.0, but the same error occurred with 4.4.0

**Comment by dirodriguezHMS** [comment]
Did you find a workaround for this? Having the same issue in my local environment using docker.

**Comment by miwurster** [comment]
No, unfortunately not. The project, or at least the community here, seems to be "dead". Atm we are evaluating different solutions that my self-host. However, the only possible way to go with Fossology IMHO would be through a managed hosting like offered by the AWS Marketplace.

**Comment by lmarie23** [comment]
I have a similar issue, not exactly the same. 
My guess is to focus on line " Old release was " which do not show anything. 
It means that this information is not set at first db initialization, and then when restarting fossology face issue populating again the database. 
I just start digging

**Comment by lmarie23** [comment]
I think I found the commit that changed the behavior : https://github.com/fossology/fossology/commit/e08eeb71f012c4f661aa15f63088e03ba332b162#diff-652dd03bfdc338852b5f8a14cb7f323ec4b482813c05ed2b1445baa05d7420f1L399

I don't know if this VERSION file is generated, but it is in .gitignore, so when building the image I don't have it. 
Maybe @GMishx can answer ?

**Comment by DhanashreePetare** [comment]
I am interested to work on the issue. Can you assign me the same if its available.

**Comment by lmarie23** [comment]
Any update regarding this issue ?

**Comment by shaheemazmalmmd** [comment]
This issue shall be fixed by https://github.com/fossology/fossology/pull/3228  the problem is we are not able to reproduce it on our side. can someone of you do a quick check ?

**Comment by Shivangisriva** [comment]
I will verify and be back to you.

**Comment by Shivangisriva** [comment]
I have reviewed the code and description in PR #3228. The changes look correct and directly address the root cause of this issue by ensuring the VERSION file is properly handled and preventing repeated schema migrations. Based on the implementation, this should resolve the “column already exists” errors after container restarts.
