### ISSUE TITLE
Error when running post installation script

### ISSUE THREAD

**Issue by pozos1096** [fossology/fossology#2807]
### Description

I'm having trouble running the post-installation script for Fossology as outlined in the [installation guide](https://github.com/fossology/fossology/wiki/Install-from-Source).

#### How to reproduce

When I execute the script with the following command:
```bash
sudo /usr/local/lib/fossology/fo-postinstall

I receive the following error message:
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-paao6nic/progress/setup.py'"'"'; __file__='"'"'/tmp/pip-install-paao6nic/progress/setup.py'"'"'; f=getattr(tokenize, '"'"'open'"'"', open)(__file__); code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"'); f.close(); exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-paao6nic/progress/pip-egg-info
cwd: /tmp/pip-install-paao6nic/progress/
Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/fossy/pythondeps/setuptools/__init__.py", line 21, in <module>
        from .dist import Distribution
      File "/home/fossy/pythondeps/setuptools/dist.py", line 29, in <module>
        from . import _entry_points
      File "/home/fossy/pythondeps/setuptools/_entry_points.py", line 44, in <module>
        def validate(eps: metadata.EntryPoints):
    AttributeError: module 'importlib_metadata' has no attribute 'EntryPoints'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info
Check the logs for full command output.

### Versions

Fossology version: 4.4.0
Python version: 3.8.10
importlib_metadata version: 1.5.0
setuptools version: 71.0.0

**Comment by dineshr93** [comment]
> AttributeError: module 'importlib_metadata' has no attribute 'EntryPoints'

Can you try again after installing these libs mentioned in the link in this comment?  https://github.com/pypa/setuptools/issues/4478#issuecomment-2235160778

**Comment by pozos1096** [comment]
Thank you @dineshr93 after installing those versions of libs installation was succesfull.

**Comment by pozos1096** [comment]
Closing this issue as per issue is solved.
