### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getRisk() on null in /usr/local/share/fossology/lib/php/Report/LicenseMainGetter.php:44

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#2833]
### Description

generating readmeoss report throws below error

#### logs

```
PHP Fatal error:  Uncaught Error: Call to a member function getRisk() on null in /usr/local/share/fossology/lib/php/Report/LicenseMainGetter.php:44"
 "Stack trace:"
 "#0 /usr/local/share/fossology/lib/php/Report/LicenseMainGetter.php(57): Fossology\Lib\Report\LicenseMainGetter->getStatements()"
 "#1 /usr/local/share/fossology/readmeoss/agent/readmeoss.php(127): Fossology\Lib\Report\LicenseMainGetter->getCleared()"
 "#2 /usr/local/share/fossology/lib/php/Agent/Agent.php(328): ReadmeOssAgent->processUploadId()"
 "#3 /usr/local/share/fossology/readmeoss/agent/readmeoss.php(242): Fossology\Lib\Agent\Agent->run_scheduler_event_loop()"
 "#4 /usr/local/lib/fossology/fo_wrapper(65): require('/usr/local/shar...')"
 "#5 {main}"
 "  thrown in /usr/local/share/fossology/lib/php/Report/LicenseMainGetter.php on line 44
 agent failed, code: 255
```

### Versions

* Last commit id on master: Version: [4.4.0.63], Branch: [master], Commit: [#4e8e87] 2024/06/12 10:07 +00:00 built @ 2024/06/24 17:25 +00:00
* Operating System (lsb_release -a):  Ubuntu 20.04.6 LTS

**Comment by shaheemazmalmmd** [comment]
@dineshr93 : can you please explain the clearing process involved in this ? example like in which group you have cleared this component and in which group this component is being cleared ?? and also let me know if the candidate license is being used ?

**Comment by SalmanDeveloperz** [comment]
Hi @shaheemazmalmmd ,
It seems like no one is working on it. Can I work on this issue?

**Comment by chaitanyarai19** [comment]
Hi @dineshr93 ,
Could you please assign this issue to me? I'd like to work on resolving the PHP Fatal error: Uncaught Error: Call to a member function getRisk() on null in LicenseMainGetter.php.

Thanks!

**Comment by shaheemazmalmmd** [comment]
@chaitanyarai19 : Seems like the issue is already closed by #2997
