### ISSUE TITLE
[Admin -> Maintenance] "Run all maintenance operations." crashes with log error text displayed.

### ISSUE THREAD

**Issue by pguttmann** [fossology/fossology#412]
Error message from /var/log/apache2/error.log -:

[Mon Mar 30 17:28:17.424909 2015] [:error] [pid 20237] [client a.b.c.d:p] PHP Warning:  pg_execute(): Query failed: ERROR:  invalid input syntax for integer: &quot;Maintenance&quot; in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 72, referer: http://w.x.y.z/repo/?mod=maintagent
[Mon Mar 30 17:28:17.425164 2015] [:error] [pid 20237] [client a.b.c.d:p] [2015-03-30 17:28:17] default.CRITICAL: ERROR:  invalid input syntax for integer: "Maintenance" [] [], referer: http://w.x.y.z/repo/?mod=maintagent
[Mon Mar 30 17:28:17.425315 2015] [:error] [pid 20237] [client a.b.c.d:p] PHP Fatal error:  Uncaught exception 'Fossology\\Lib\\Exception' with message 'error executing: JobAddJob: INSERT INTO job\n    (job_user_fk,job_group_fk,job_queued,job_priority,job_name,job_upload_fk) VALUES\n    ($1,$5,now(),$2,$3,$4) RETURNING job_pk -- -- Array\n(\n    [0] => 2\n    [1] => 0\n    [2] => 0\n    [3] => \n    [4] => Maintenance\n)\n\n\nERROR:  invalid input syntax for integer: "Maintenance"' in /usr/local/share/fossology/lib/php/Db/DbManager.php:120\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Db/ModernDbManager.php(71): Fossology\\Lib\\Db\\DbManager->checkResult(false, 'JobAddJob: INSE...')\n#1 /usr/local/share/fossology/lib/php/Db/DbManager.php(141): Fossology\\Lib\\Db\\ModernDbManager->execute('JobAddJob', Array)\n#2 /usr/local/share/fossology/lib/php/common-job.php(134): Fossology\\Lib\\Db\\DbManager->getSingleRow('INSERT INTO job...', Array, 'JobAddJob')\n#3 /usr/local/share/fossology/maintagent/ui/maintagent.php(52): JobAddJob('2', 'Maintenance', 0)\n#4 /usr/local/share/fossology/maintagent/ui/maintagent.php(130): maintagen in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 120, referer: http://w.x.y.z/repo/?mod=maintagent

**Comment by pguttmann** [comment]
Confirmed fixed and running as expected with latest code. Thanks again for the quick fix !!!
