### ISSUE TITLE
clearing_decision constraint failure

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#438]
I just updated to 8bba20c and am getting the following error from fo-postinstall apparently caused by a new clearing_decision contstraint.  Is it possible for 2.6.2 users to run into this?

```
*** update the database and license_ref table ***
PHP Warning:  pg_query(): Query failed: ERROR:  duplicate key value violates unique constraint "clearing_decision_pkey"
DETAIL:  Key (clearing_decision_pk)=(9) already exists. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 81
PHP Stack trace:
PHP   1. {main}() /usr/local/lib/fossology/fossinit.php:0
PHP   2. fo_libschema->applySchema() /usr/local/lib/fossology/fossinit.php:140
PHP   3. fo_libschema->applyTables() /usr/local/share/fossology/lib/php/libschema.php:142
PHP   4. Fossology\Lib\Db\DbManager->queryOnce() /usr/local/share/fossology/lib/php/libschema.php:282
PHP   5. Fossology\Lib\Db\Driver\Postgres->query() /usr/local/share/fossology/lib/php/Db/DbManager.php:159
PHP   6. pg_query() /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php:81
[2015-05-20 13:50:47] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  duplicate key value violates unique constraint "clearing_decision_pkey" DETAIL:  Key (clearing_decision_pk)=(9) already exists. [] []
PHP Fatal error:  Uncaught exception 'Fossology\Lib\Exception' with message 'error executing: UPDATE clearing_decision SET clearing_decision_pk=nextval('clearing_decision_clearing_decision_pk_seq'::regclass)

ERROR:  duplicate key value violates unique constraint "clearing_decision_pkey"
DETAIL:  Key (clearing_decision_pk)=(9) already exists.' in /usr/local/share/fossology/lib/php/Db/DbManager.php:120
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(160): Fossology\Lib\Db\DbManager->checkResult(false, 'UPDATE clearing...')
#1 /usr/local/share/fossology/lib/php/libschema.php(282): Fossology\Lib\Db\DbManager->queryOnce('UPDATE clearing...')
#2 /usr/local/share/fossology/lib/php/libschema.php(142): fo_libschema->applyTables()
#3 /usr/local/lib/fossology/fossinit.php(140): fo_libschema->applySchema('/usr/local/shar...', false, 'fossology', Array)
#4 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 120
Database connectivity is good.
*** Setting up scheduler ***
```

**Comment by steffen-weber** [comment]
Since e3392e0418a5860813358b20aaaebd7a97ff33b0, core-schema.dat has default values in the "ADD" queries instead of "UPDATE" queries. Hence, the invalid state before delayed value update is skipped.
For verification, I checked out 2.6.2, made fresh install, run fo-postinstall, made some decisions, checked out latest (1248f4146a73f45fda7f22ad918ff5895fe815f5), made install and run fo-postinstall without error:
```
...
Ensure that every user had chosen an active groupLink decisions with groups
Fill clearing event table with old decisions... and link them with decisions
Adding link to real parent in uploadtree table
...
```
