### ISSUE TITLE
Fatal error in mod=copyright-list when copyright analysis hasn't been run

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#745]
To reproduce:

1. Upload any file and run only a Nomos analysis
2. Navigate to the browse page and select `Copyright/Email/Url` for this file
3. Page will not load, error will be seen in logs

The following can be seen in `/var/log/apache2/error.log`:

```
[Fri Feb 17 16:20:24.652422 2017] [:error] [pid 1001] [client 192.168.99.1:52710] PHP Warning:  pg_prepare(): Query failed: ERROR:  relation &quot;copyright_ars&quot; does not exist\nLINE 1: SELECT * FROM (SELECT agent_pk, agent_name FROM copyright_ar...\n                                                        ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 62, referer: https://docker.localhost/?mod=browse
[Fri Feb 17 16:20:24.652607 2017] [:error] [pid 1001] [client 192.168.99.1:52710] [2017-02-17 16:20:24] default.CRITICAL: ERROR:  relation "copyright_ars" does not exist LINE 1: SELECT * FROM (SELECT agent_pk, agent_name FROM copyright_ar...                                                         ^ [] [], referer: https://docker.localhost/?mod=browse
[Fri Feb 17 16:20:24.652703 2017] [:error] [pid 1001] [client 192.168.99.1:52710] PHP Fatal error:  Uncaught Fossology\\Lib\\Exception: error executing: SELECT * FROM (SELECT agent_pk, agent_name FROM copyright_ars, agent\n        WHERE agent_fk=agent_pk AND upload_fk=4 AND agent_enabled ORDER BY agent_fk DESC limit 1) latest_copyright -- Fossology\\Lib\\Proxy\\LatestScannerProxy::getNameToIdMap.latest_scanner4_copyright\n\nERROR:  relation "copyright_ars" does not exist\nLINE 1: SELECT * FROM (SELECT agent_pk, agent_name FROM copyright_ar...\n                                                        ^ in /usr/local/share/fossology/lib/php/Db/DbManager.php:120\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Db/ModernDbManager.php(51): Fossology\\Lib\\Db\\DbManager->checkResult(false, 'SELECT * FROM (...')\n#1 /usr/local/share/fossology/lib/php/Proxy/LatestScannerProxy.php(86): Fossology\\Lib\\Db\\ModernDbManager->prepare('Fossology\\\\Lib\\\\P...', 'SELECT * FROM (...')\n#2 /usr/local/share/fossology/lib/php/Dao/AgentDao.php(210): Fossology\\Lib\\Proxy\\LatestScannerProxy->getNameToIdMap()\n#3 /usr/local/share/fossology/copyright/u in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 120, referer: https://docker.localhost/?mod=browse
```

Tested on Version: [3.1.0rc2], Branch: [master], Commit: [#3b080b]

**Comment by GMishx** [comment]
This seems like an issue on a fresh instance where copyright have not run even a single time. As the error says `ERROR:  relation "copyright_ars" does not exist`. The missing `copyright_ars` relation is created by copyright agent on its first run.

On an instance with `copyright_ars`, the issue does not appears. The user is informed that "Copyright agent has not scheduled" and simple button appears on the page to schedule it.

**Comment by shaheemazmalmmd** [comment]
Issue can be closed as schedule option is already there for any agent which is not scheduled.
